port: 7890
socks-port: 1080 # SOCKS5代理端口，DNS请求会中转
redir-port: 3333 # 透明代理端口
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
secret: route

# 透明代理开启DNS
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: true # lookup hosts and return IP record
  nameserver:
  - tls://doh.pub:853   # DNSpod DoT
  - https://doh.pub/dns-query   # DNSpod DoH
  - 119.29.29.29   # DNSpod DNS 17ms
  # 提供 fallback 时，如果GEOIP非 CN 中国时使用 fallback 解析
  fallback:
  - tls://8.8.8.8:853   # Google DNS over TLS
  - tls://1.1.1.1:853   # cloudflare DNS over TLS
  - https://dns.google/dns-query   # Google DNS over HTTPS
  - https://cloudflare-dns.com/dns-query   # cloudflare DNS over HTTPS
  # 强制DNS解析使用`fallback`配置
  fallback-filter:
    # true: CN使用nameserver解析，非CN使用fallback
    geoip: true
    # geoip设置为false时有效： 不匹配`ipcidr`地址时会使用`nameserver`结果，匹配`ipcidr`地址时使用`fallback`结果。
    ipcidr:
    - 240.0.0.0/4


# 配置规则参考文档： https://github.com/Dreamacro/clash/wiki/configuration
# 设置代理提供者(远程订阅地址+本地订阅文件)
# proxy-providers:
#   provider_file:
#     type: file
#     path: ./provider_local.yaml
#     health-check:
#       enable: true
#       interval: 600
#       url: http://www.gstatic.com/generate_204
#   provider_url:
#     type: file
#     path: ./provider_remote.yaml
#     health-check:
#       enable: true
#       interval: 600
#       url: http://www.gstatic.com/generate_204
#
#
# DIY组保留的个人节点
proxies:
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:45746
  type: ss
  server: 156.146.62.37
  port: 45746
  cipher: aes-256-gcm
  password: wEsFcHCvbL4eJkL4DZQa7RgR
- name: 🇸🇬新加坡-0-0-ss-172.107.233.234:2376
  type: ss
  server: 172.107.233.234
  port: 2376
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:36460
  type: ss
  server: 156.146.62.37
  port: 36460
  cipher: aes-256-gcm
  password: yUXad7DGF8L5cTShEpnp2N6z
- name: 🇸🇬新加坡-0-0-ss-172.107.233.230:2376
  type: ss
  server: 172.107.233.230
  port: 2376
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇺🇸美国-康涅狄格-0-ss-172.99.190.158:2375
  type: ss
  server: 172.99.190.158
  port: 2375
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇺🇸美国-0-0-ss-134.195.196.202:7306
  type: ss
  server: 134.195.196.202
  port: 7306
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-167.88.63.99:2375
  type: ss
  server: 167.88.63.99
  port: 2375
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇺🇸美国-康涅狄格-0-ss-172.99.190.153:2375
  type: ss
  server: 172.99.190.153
  port: 2375
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇷🇴罗马尼亚-布加勒斯特-0-ss-45.89.173.205:41676
  type: ss
  server: 45.89.173.205
  port: 41676
  cipher: aes-256-gcm
  password: z6pH3RyttkRWhJ5tpRyt6dYk
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:44745
  type: ss
  server: 156.146.62.37
  port: 44745
  cipher: aes-256-gcm
  password: fyXdw87yCH9SAmFkPvsvLVqC
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-167.88.63.11:2376
  type: ss
  server: 167.88.63.11
  port: 2376
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-167.88.63.11:7306
  type: ss
  server: 167.88.63.11
  port: 7306
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:49719
  type: ss
  server: 156.146.33.74
  port: 49719
  cipher: aes-256-gcm
  password: 42SjT9vBF6ma9eFF3URaJpQ4
- name: 🇷🇸塞尔维亚-0-0-ss-152.89.160.61:40093
  type: ss
  server: 152.89.160.61
  port: 40093
  cipher: aes-256-gcm
  password: x23Z4LGkGDkThZ9Kaz4DURQp
- name: 🇦🇿阿塞拜疆-0-0-ss-62.212.239.53:48938
  type: ss
  server: 62.212.239.53
  port: 48938
  cipher: aes-256-gcm
  password: 4ejJ8n5ddLuYDUHGXJre2ufJ
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:39720
  type: ss
  server: 156.146.62.37
  port: 39720
  cipher: aes-256-gcm
  password: kq8xQKC3K4jYQPwLXTNbJjm6
- name: 🇺🇸美国-0-0-ss-134.195.198.178:2376
  type: ss
  server: 134.195.198.178
  port: 2376
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇩🇪德国-黑森-0-ss-145.239.1.137:7307
  type: ss
  server: 145.239.1.137
  port: 7307
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:31572
  type: ss
  server: 198.147.22.87
  port: 31572
  cipher: aes-256-gcm
  password: n8w4StnbVD9dmXYn4Ajt87EA
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:49719
  type: ss
  server: 156.146.62.37
  port: 49719
  cipher: aes-256-gcm
  password: 42SjT9vBF6ma9eFF3URaJpQ4
- name: 🇺🇸美国-0-0-ss-134.195.196.202:5003
  type: ss
  server: 134.195.196.202
  port: 5003
  cipher: aes-256-gcm
  password: g5MeD6Ft3CWlJId
- name: 🇺🇸美国-康涅狄格-0-ss-172.99.190.153:8090
  type: ss
  server: 172.99.190.153
  port: 8090
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:45948
  type: ss
  server: 156.146.62.37
  port: 45948
  cipher: aes-256-gcm
  password: j76EXqJcQhuQTr3EvUf7xaK9
- name: 🇺🇸美国-0-0-ss-134.195.196.202:8090
  type: ss
  server: 134.195.196.202
  port: 8090
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-167.88.63.11:8090
  type: ss
  server: 167.88.63.11
  port: 8090
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 🇷🇴罗马尼亚-布加勒斯特-0-ss-45.89.173.205:48938
  type: ss
  server: 45.89.173.205
  port: 48938
  cipher: aes-256-gcm
  password: 4ejJ8n5ddLuYDUHGXJre2ufJ
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:41372
  type: ss
  server: 156.146.62.37
  port: 41372
  cipher: aes-256-gcm
  password: 5kGAhC3AmVC35GbruHjSrZf2
- name: 🇺🇸美国-0-0-ss-134.195.196.179:3389
  type: ss
  server: 134.195.196.179
  port: 3389
  cipher: aes-256-gcm
  password: Y6R9pAtvxxzmGC
- name: 🇦🇿阿塞拜疆-0-0-ss-62.212.239.53:35294
  type: ss
  server: 62.212.239.53
  port: 35294
  cipher: aes-256-gcm
  password: J9Y2ncrdPEC38gwydNFFGBna
- name: 🇨🇳中国-上海-上海-ss-101.91.121.247:50004
  type: ss
  server: 101.91.121.247
  port: 50004
  cipher: aes-256-cfb
  password: '4415934295'
- name: 🇳🇴挪威-Oslo-0-ss-91.219.215.19:31944
  type: ss
  server: 91.219.215.19
  port: 31944
  cipher: aes-256-gcm
  password: aYNeKDMzYQYw4KbUbJA8Wszq
- name: 🇺🇸美国-德克萨斯-0-ss-38.107.226.49:2375
  type: ss
  server: 38.107.226.49
  port: 2375
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-167.88.63.99:7307
  type: ss
  server: 167.88.63.99
  port: 7307
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 🇷🇸塞尔维亚-0-0-ss-152.89.160.61:50024
  type: ss
  server: 152.89.160.61
  port: 50024
  cipher: aes-256-gcm
  password: b2jDPHUQxCNa2KmGHZjy7C4B
- name: 🇺🇸美国-德克萨斯-0-ss-38.107.226.49:3306
  type: ss
  server: 38.107.226.49
  port: 3306
  cipher: aes-256-gcm
  password: Y6R9pAtvxxzmGC
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:44742
  type: ss
  server: 156.146.62.37
  port: 44742
  cipher: aes-256-gcm
  password: QCStKzZ56SHBc4tL7stCEqqd
- name: 🇦🇿阿塞拜疆-0-0-ss-62.212.239.53:33998
  type: ss
  server: 62.212.239.53
  port: 33998
  cipher: aes-256-gcm
  password: NHwQTPLCfaTMSqTnU3mjcSxe
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:46726
  type: ss
  server: 198.8.92.84
  port: 46726
  cipher: aes-256-gcm
  password: 2fqKbFPGHpcmMTJzGsUbsfYf
- name: 🇺🇸美国-德克萨斯-0-ss-38.107.226.49:7306
  type: ss
  server: 38.107.226.49
  port: 7306
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 🇮🇹意大利-米兰-米兰-ss-82.102.26.94:38742
  type: ss
  server: 82.102.26.94
  port: 38742
  cipher: aes-256-gcm
  password: DKXfWwc4ebscpXTKpbt85rSH
- name: 🇺🇸美国-德克萨斯-0-ss-38.107.226.159:2376
  type: ss
  server: 38.107.226.159
  port: 2376
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇺🇸美国-康涅狄格-0-ss-172.99.190.153:7306
  type: ss
  server: 172.99.190.153
  port: 7306
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:49202
  type: ss
  server: 156.146.62.37
  port: 49202
  cipher: aes-256-gcm
  password: btzEYXKZxnR7g6H2vFTQK5TD
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-167.88.63.99:2376
  type: ss
  server: 167.88.63.99
  port: 2376
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-66.115.177.141:50168
  type: ss
  server: 66.115.177.141
  port: 50168
  cipher: aes-256-gcm
  password: WCuz7yrfZSCQQXSNrtGPz2HT
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:38033
  type: ss
  server: 156.146.62.37
  port: 38033
  cipher: aes-256-gcm
  password: xpQwyV4W5FdA6NMANJJx73US
- name: 🇺🇸美国-0-0-ss-134.195.196.60:5003
  type: ss
  server: 134.195.196.60
  port: 5003
  cipher: aes-256-gcm
  password: g5MeD6Ft3CWlJId
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-167.88.63.82:8090
  type: ss
  server: 167.88.63.82
  port: 8090
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 🇨🇳中国-福建-泉州-ssr-117.28.242.137:9359
  type: ssr
  server: 117.28.242.137
  password: '73117962'
  obfs: plain
  protocol: origin
  port: 9359
  cipher: aes-256-cfb
  protocol-param: ''
  obfs-param: ''

proxy-groups:
# 类型选择 简介
# select : 用于选择代理或代理组, 可以通过 RESTful API 来切换代理，建议在 GUI 中使用
# load-balance : 相同eTLD+1的请求将拨号到同一个代理。
# url-test : 通过对 URL 的速度进行基准测试来选择将使用哪个代理。
# fallback : 按优先级选择可用的策略。通过访问 URL 来测试可用性，就像自动 url-test 组一样。
# relay : 中继链接代理。代理不应包含中继。不支持 UDP。 流量：Clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet 
#  
# 推荐选择：
#   命令行服务建议选择 url-test / fallback / load-balance
#   GUI窗口 官方建议选择 select ，当然也推荐使用url-test 自动检测可用性。
- name: PROXY
  type: select   # load-balance, select, relay, fallback, url-test
  tolerance: 300
    # lazy: true
  url: http://www.gstatic.com/generate_204
  interval: 300
    # strategy: consistent-hashing # or round-robin  # 负载均衡策略
  proxies:
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:49719
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:49202
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:45948
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:45746
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:44745
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:44742
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:41372
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:39720
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:38033
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:36460
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:49719
  - 🇺🇸美国-德克萨斯-0-ss-38.107.226.49:7306
  - 🇺🇸美国-德克萨斯-0-ss-38.107.226.49:3306
  - 🇺🇸美国-德克萨斯-0-ss-38.107.226.49:2375
  - 🇺🇸美国-德克萨斯-0-ss-38.107.226.159:2376
  - 🇺🇸美国-康涅狄格-0-ss-172.99.190.158:2375
  - 🇺🇸美国-康涅狄格-0-ss-172.99.190.153:8090
  - 🇺🇸美国-康涅狄格-0-ss-172.99.190.153:7306
  - 🇺🇸美国-康涅狄格-0-ss-172.99.190.153:2375
  - 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:31572
  - 🇺🇸美国-佐治亚-亚特兰大-ss-66.115.177.141:50168
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:46726
  - 🇺🇸美国-佐治亚-亚特兰大-ss-167.88.63.99:7307
  - 🇺🇸美国-佐治亚-亚特兰大-ss-167.88.63.99:2376
  - 🇺🇸美国-佐治亚-亚特兰大-ss-167.88.63.99:2375
  - 🇺🇸美国-佐治亚-亚特兰大-ss-167.88.63.82:8090
  - 🇺🇸美国-佐治亚-亚特兰大-ss-167.88.63.11:8090
  - 🇺🇸美国-佐治亚-亚特兰大-ss-167.88.63.11:7306
  - 🇺🇸美国-佐治亚-亚特兰大-ss-167.88.63.11:2376
  - 🇺🇸美国-0-0-ss-134.195.198.178:2376
  - 🇺🇸美国-0-0-ss-134.195.196.60:5003
  - 🇺🇸美国-0-0-ss-134.195.196.202:8090
  - 🇺🇸美国-0-0-ss-134.195.196.202:7306
  - 🇺🇸美国-0-0-ss-134.195.196.202:5003
  - 🇺🇸美国-0-0-ss-134.195.196.179:3389
  - 🇸🇬新加坡-0-0-ss-172.107.233.234:2376
  - 🇸🇬新加坡-0-0-ss-172.107.233.230:2376
  - 🇷🇸塞尔维亚-0-0-ss-152.89.160.61:50024
  - 🇷🇸塞尔维亚-0-0-ss-152.89.160.61:40093
  - 🇷🇴罗马尼亚-布加勒斯特-0-ss-45.89.173.205:48938
  - 🇷🇴罗马尼亚-布加勒斯特-0-ss-45.89.173.205:41676
  - 🇳🇴挪威-Oslo-0-ss-91.219.215.19:31944
  - 🇮🇹意大利-米兰-米兰-ss-82.102.26.94:38742
  - 🇩🇪德国-黑森-0-ss-145.239.1.137:7307
  - 🇨🇳中国-福建-泉州-ssr-117.28.242.137:9359
  - 🇨🇳中国-上海-上海-ss-101.91.121.247:50004
  - 🇦🇿阿塞拜疆-0-0-ss-62.212.239.53:48938
  - 🇦🇿阿塞拜疆-0-0-ss-62.212.239.53:35294
  - 🇦🇿阿塞拜疆-0-0-ss-62.212.239.53:33998
rules:
  # 黑名单模式，命中规则使用代理
- PROCESS-NAME,v2ray,DIRECT
- PROCESS-NAME,xray,DIRECT
- PROCESS-NAME,naive,DIRECT
- PROCESS-NAME,trojan,DIRECT
- PROCESS-NAME,trojan-go,DIRECT
- PROCESS-NAME,ss-local,DIRECT
- PROCESS-NAME,privoxy,DIRECT
- PROCESS-NAME,leaf,DIRECT
- PROCESS-NAME,v2ray.exe,DIRECT
- PROCESS-NAME,xray.exe,DIRECT
- PROCESS-NAME,naive.exe,DIRECT
- PROCESS-NAME,trojan.exe,DIRECT
- PROCESS-NAME,trojan-go.exe,DIRECT
- PROCESS-NAME,ss-local.exe,DIRECT
- PROCESS-NAME,privoxy.exe,DIRECT
- PROCESS-NAME,leaf.exe,DIRECT
- PROCESS-NAME,Surge,DIRECT
- PROCESS-NAME,Surge 2,DIRECT
- PROCESS-NAME,Surge 3,DIRECT
- PROCESS-NAME,Surge 4,DIRECT
- PROCESS-NAME,Surge%202,DIRECT
- PROCESS-NAME,Surge%203,DIRECT
- PROCESS-NAME,Surge%204,DIRECT
- PROCESS-NAME,Thunder,DIRECT
- PROCESS-NAME,DownloadService,DIRECT
- PROCESS-NAME,qBittorrent,DIRECT
- PROCESS-NAME,Transmission,DIRECT
- PROCESS-NAME,fdm,DIRECT
- PROCESS-NAME,aria2c,DIRECT
- PROCESS-NAME,Folx,DIRECT
- PROCESS-NAME,NetTransport,DIRECT
- PROCESS-NAME,uTorrent,DIRECT
- PROCESS-NAME,WebTorrent,DIRECT
- PROCESS-NAME,aria2c.exe,DIRECT
- PROCESS-NAME,BitComet.exe,DIRECT
- PROCESS-NAME,fdm.exe,DIRECT
- PROCESS-NAME,NetTransport.exe,DIRECT
- PROCESS-NAME,qbittorrent.exe,DIRECT
- PROCESS-NAME,Thunder.exe,DIRECT
- PROCESS-NAME,ThunderVIP.exe,DIRECT
- PROCESS-NAME,transmission-daemon.exe,DIRECT
- PROCESS-NAME,transmission-qt.exe,DIRECT
- PROCESS-NAME,uTorrent.exe,DIRECT
- PROCESS-NAME,WebTorrent.exe,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- GEOIP,CN,DIRECT
- MATCH,PROXY
