port: 7890
socks-port: 1080 # SOCKS5代理端口，DNS请求会中转
redir-port: 3333 # 透明代理端口
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
secret: route

# 透明代理开启DNS
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: true # lookup hosts and return IP record
  nameserver:
  - tls://doh.pub:853   # DNSpod DoT
  - https://doh.pub/dns-query   # DNSpod DoH
  - 119.29.29.29   # DNSpod DNS 17ms
  # 提供 fallback 时，如果GEOIP非 CN 中国时使用 fallback 解析
  fallback:
  - tls://8.8.8.8:853   # Google DNS over TLS
  - tls://1.1.1.1:853   # cloudflare DNS over TLS
  - https://dns.google/dns-query   # Google DNS over HTTPS
  - https://cloudflare-dns.com/dns-query   # cloudflare DNS over HTTPS
  # 强制DNS解析使用`fallback`配置
  fallback-filter:
    # true: CN使用nameserver解析，非CN使用fallback
    geoip: true
    # geoip设置为false时有效： 不匹配`ipcidr`地址时会使用`nameserver`结果，匹配`ipcidr`地址时使用`fallback`结果。
    ipcidr:
    - 240.0.0.0/4


# 配置规则参考文档： https://github.com/Dreamacro/clash/wiki/configuration
# 设置代理提供者(远程订阅地址+本地订阅文件)
# proxy-providers:
#   provider_file:
#     type: file
#     path: ./provider_local.yaml
#     health-check:
#       enable: true
#       interval: 600
#       url: http://www.gstatic.com/generate_204
#   provider_url:
#     type: file
#     path: ./provider_remote.yaml
#     health-check:
#       enable: true
#       interval: 600
#       url: http://www.gstatic.com/generate_204
#
#
# DIY组保留的个人节点
proxies:
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:40220
  type: ss
  server: 156.146.62.37
  port: 40220
  cipher: aes-256-gcm
  password: ugyBkSEFxVEmUYSHyvxmWNj9
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:36460
  type: ss
  server: 156.146.62.37
  port: 36460
  cipher: aes-256-gcm
  password: yUXad7DGF8L5cTShEpnp2N6z
- name: 🇨🇦加拿大-安大略-多伦多-ss-198.57.27.218:2376
  type: ss
  server: 198.57.27.218
  port: 2376
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:2376
  type: ss
  server: 46.29.218.6
  port: 2376
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:37588
  type: ss
  server: 156.146.62.37
  port: 37588
  cipher: aes-256-gcm
  password: kD9vkjnE6dsUzwQfvKkPkQAd
- name: 🇨🇳中国-福建-泉州-ss-117.28.243.132:8333
  type: ss
  server: 117.28.243.132
  port: 8333
  cipher: rc4-md5
  password: passfw2xs4e!
- name: 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:8090
  type: ss
  server: 46.29.218.6
  port: 8090
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 🇨🇦加拿大-安大略-多伦多-ss-198.57.27.218:8090
  type: ss
  server: 198.57.27.218
  port: 8090
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:41676
  type: ss
  server: 156.146.62.37
  port: 41676
  cipher: aes-256-gcm
  password: z6pH3RyttkRWhJ5tpRyt6dYk
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:49202
  type: ss
  server: 156.146.62.37
  port: 49202
  cipher: aes-256-gcm
  password: btzEYXKZxnR7g6H2vFTQK5TD
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:42816
  type: ss
  server: 156.146.62.37
  port: 42816
  cipher: aes-256-gcm
  password: tBKBf4pVzNCFKdbPgvwrNXq3
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:39171
  type: ss
  server: 156.146.62.37
  port: 39171
  cipher: aes-256-gcm
  password: z4pM2gA9QEEC6NRmqTQubm6Z
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:48938
  type: ss
  server: 156.146.62.37
  port: 48938
  cipher: aes-256-gcm
  password: 4ejJ8n5ddLuYDUHGXJre2ufJ
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:40093
  type: ss
  server: 156.146.62.37
  port: 40093
  cipher: aes-256-gcm
  password: x23Z4LGkGDkThZ9Kaz4DURQp
- name: 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:33992
  type: ss
  server: 198.147.22.87
  port: 33992
  cipher: aes-256-gcm
  password: 8n6pwAcrrv2pj6tFY2p3TbQ6
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:44820
  type: ss
  server: 156.146.62.37
  port: 44820
  cipher: aes-256-gcm
  password: jspgz9G3VmvBMCgMUWLBaZHu
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:37473
  type: ss
  server: 156.146.62.37
  port: 37473
  cipher: aes-256-gcm
  password: enctdKyJfSu76VqznKwTt6Ap
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:35294
  type: ss
  server: 156.146.62.37
  port: 35294
  cipher: aes-256-gcm
  password: J9Y2ncrdPEC38gwydNFFGBna
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:43963
  type: ss
  server: 156.146.62.37
  port: 43963
  cipher: aes-256-gcm
  password: Tuw6zzZM6JwWNZyYF9ckC4JZ
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:46412
  type: ss
  server: 156.146.62.37
  port: 46412
  cipher: aes-256-gcm
  password: GEqk9WGyybeyXW97YEdanDYs
- name: 🇺🇸美国-加利福尼亚-费利蒙-ss-185.124.240.146:39556
  type: ss
  server: 185.124.240.146
  port: 39556
  cipher: aes-256-gcm
  password: g4AfpNELpdYEeLYhM8XCX9se
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:45948
  type: ss
  server: 156.146.62.37
  port: 45948
  cipher: aes-256-gcm
  password: j76EXqJcQhuQTr3EvUf7xaK9
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:37559
  type: ss
  server: 156.146.62.37
  port: 37559
  cipher: aes-256-gcm
  password: Qbt22F6JsxzFGqcsK5SaR8q3
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:40282
  type: ss
  server: 156.146.62.37
  port: 40282
  cipher: aes-256-gcm
  password: Pvvaw486867D2w4yctL2ULTQ
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:38620
  type: ss
  server: 156.146.62.37
  port: 38620
  cipher: aes-256-gcm
  password: Kquv5UhvZXNMemAQy8DxZ7qn
- name: 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:7306
  type: ss
  server: 46.29.218.6
  port: 7306
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 🇺🇸美国-加利福尼亚-圣何塞-ss-167.88.61.50:7307
  type: ss
  server: 167.88.61.50
  port: 7307
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:49339
  type: ss
  server: 156.146.62.37
  port: 49339
  cipher: aes-256-gcm
  password: suucSeVLmt6PQKAP77NtGw9x
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:47553
  type: ss
  server: 156.146.62.37
  port: 47553
  cipher: aes-256-gcm
  password: t2JnnFqjDMmzWurseJPgBsYY
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:35371
  type: ss
  server: 156.146.62.37
  port: 35371
  cipher: aes-256-gcm
  password: pjeDhAJGuML8xKUxcjRqq6a9
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:42166
  type: ss
  server: 156.146.62.37
  port: 42166
  cipher: aes-256-gcm
  password: H9Dbn3szZMqLR3NpgEFEPCKb
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:38033
  type: ss
  server: 156.146.62.37
  port: 38033
  cipher: aes-256-gcm
  password: xpQwyV4W5FdA6NMANJJx73US
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:45329
  type: ss
  server: 156.146.62.37
  port: 45329
  cipher: aes-256-gcm
  password: CXSjgD7u7Ar7GxkZ4CgTMUsj
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:41306
  type: ss
  server: 156.146.62.37
  port: 41306
  cipher: aes-256-gcm
  password: pzB5Y2twNtqFzWhEbBsPJMjj
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:48970
  type: ss
  server: 156.146.62.37
  port: 48970
  cipher: aes-256-gcm
  password: ZKEsXkFbUZ2z667YA8A7cEDP
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:38742
  type: ss
  server: 156.146.62.37
  port: 38742
  cipher: aes-256-gcm
  password: DKXfWwc4ebscpXTKpbt85rSH
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:50695
  type: ss
  server: 156.146.62.37
  port: 50695
  cipher: aes-256-gcm
  password: gqtwGu9bVreJqL3FTHSVKGzy
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:44236
  type: ss
  server: 156.146.62.37
  port: 44236
  cipher: aes-256-gcm
  password: FWrXcxPZjJxAN89xLgqY3Acp
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:44102
  type: ss
  server: 156.146.62.37
  port: 44102
  cipher: aes-256-gcm
  password: zHKYS9DeAjvv43EwgDfyEg4d
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:41992
  type: ss
  server: 156.146.62.37
  port: 41992
  cipher: aes-256-gcm
  password: XmQSxDCn5ehpcq6DBYms8FJf
- name: 🇷🇴罗马尼亚-布加勒斯特-0-ss-45.89.173.205:31764
  type: ss
  server: 45.89.173.205
  port: 31764
  cipher: aes-256-gcm
  password: YgusH2MWA8PWc3p2VDsR7AVv
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:44539
  type: ss
  server: 156.146.62.37
  port: 44539
  cipher: aes-256-gcm
  password: r6hDrkP4Et6EENTS8Qy7Tcmg
- name: 🇷🇸塞尔维亚-0-0-ss-152.89.160.149:50168
  type: ss
  server: 152.89.160.149
  port: 50168
  cipher: aes-256-gcm
  password: WCuz7yrfZSCQQXSNrtGPz2HT
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:39556
  type: ss
  server: 156.146.62.37
  port: 39556
  cipher: aes-256-gcm
  password: g4AfpNELpdYEeLYhM8XCX9se
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:49653
  type: ss
  server: 156.146.62.37
  port: 49653
  cipher: aes-256-gcm
  password: Y9GcTPemHMKEkrfGQPJqFDNr
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:47121
  type: ss
  server: 156.146.62.37
  port: 47121
  cipher: aes-256-gcm
  password: CTK8GXFQgKYQErrghPJfZ6tk
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.37:46354
  type: ss
  server: 156.146.62.37
  port: 46354
  cipher: aes-256-gcm
  password: MYPKdC7n6qjL6xmJBBcrzzqS
- name: 🇨🇳中国-福建-泉州-ssr-117.28.243.132:8333
  type: ssr
  server: 117.28.243.132
  password: passfw2xs4e!
  obfs: plain
  protocol: origin
  port: 8333
  cipher: rc4-md5
  protocol-param: ''
  obfs-param: ''
- name: 🇨🇳中国-福建-泉州-ssr-117.28.243.169:8333
  type: ssr
  server: 117.28.243.169
  password: passfw2xs4e!
  obfs: plain
  protocol: origin
  port: 8333
  cipher: rc4-md5
  protocol-param: ''
  obfs-param: ''
- name: 🇺🇸美国-科罗拉多-0-v2ray-143.198.237.214:27489
  type: vmess
  server: 143.198.237.214
  network: ws
  port: 27489
  uuid: d73f027b-9a37-4e79-dd29-3a0d1e1da128
  alterId: 4
  cipher: auto
  tls: false
  ws-path: /
- name: 🇺🇸美国-0-0-v2ray-18.162.155.162:8888
  type: vmess
  server: 18.162.155.162
  network: ws
  port: 8888
  uuid: 63fc8d31-358d-3769-a3e1-0b3f9dd9f98f
  alterId: 4
  cipher: auto
  tls: false
  ws-path: /v2ray
- name: 🇨🇳中国-香港-0-v2ray-183.179.115.79:1888
  type: vmess
  server: 183.179.115.79
  network: ws
  port: 1888
  uuid: 877a0755-2f5c-30fc-9206-461cf8be3286
  alterId: 4
  cipher: auto
  tls: false
  ws-path: /

proxy-groups:
# 类型选择 简介
# select : 用于选择代理或代理组, 可以通过 RESTful API 来切换代理，建议在 GUI 中使用
# load-balance : 相同eTLD+1的请求将拨号到同一个代理。
# url-test : 通过对 URL 的速度进行基准测试来选择将使用哪个代理。
# fallback : 按优先级选择可用的策略。通过访问 URL 来测试可用性，就像自动 url-test 组一样。
# relay : 中继链接代理。代理不应包含中继。不支持 UDP。 流量：Clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet 
#  
# 推荐选择：
#   命令行服务建议选择 url-test / fallback / load-balance
#   GUI窗口 官方建议选择 select ，当然也推荐使用url-test 自动检测可用性。
- name: PROXY
  type: select   # load-balance, select, relay, fallback, url-test
  tolerance: 300
    # lazy: true
  url: http://www.gstatic.com/generate_204
  interval: 300
    # strategy: consistent-hashing # or round-robin  # 负载均衡策略
  proxies:
  - 🇺🇸美国-科罗拉多-0-v2ray-143.198.237.214:27489
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:50695
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:49653
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:49339
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:49202
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:48970
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:48938
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:47553
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:47121
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:46412
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:46354
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:45948
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:45329
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:44820
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:44539
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:44236
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:44102
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:43963
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:42816
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:42166
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:41992
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:41676
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:41306
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:40282
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:40220
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:40093
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:39556
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:39171
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:38742
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:38620
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:38033
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:37588
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:37559
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:37473
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:36460
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:35371
  - 🇺🇸美国-新泽西-0-ss-156.146.62.37:35294
  - 🇺🇸美国-加利福尼亚-费利蒙-ss-185.124.240.146:39556
  - 🇺🇸美国-加利福尼亚-圣何塞-ss-167.88.61.50:7307
  - 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:33992
  - 🇺🇸美国-0-0-v2ray-18.162.155.162:8888
  - 🇷🇸塞尔维亚-0-0-ss-152.89.160.149:50168
  - 🇷🇴罗马尼亚-布加勒斯特-0-ss-45.89.173.205:31764
  - 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:8090
  - 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:7306
  - 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:2376
  - 🇨🇳中国-香港-0-v2ray-183.179.115.79:1888
  - 🇨🇳中国-福建-泉州-ssr-117.28.243.169:8333
  - 🇨🇳中国-福建-泉州-ssr-117.28.243.132:8333
  - 🇨🇳中国-福建-泉州-ss-117.28.243.132:8333
  - 🇨🇦加拿大-安大略-多伦多-ss-198.57.27.218:8090
  - 🇨🇦加拿大-安大略-多伦多-ss-198.57.27.218:2376
rules:
  # 黑名单模式，命中规则使用代理
- PROCESS-NAME,v2ray,DIRECT
- PROCESS-NAME,xray,DIRECT
- PROCESS-NAME,naive,DIRECT
- PROCESS-NAME,trojan,DIRECT
- PROCESS-NAME,trojan-go,DIRECT
- PROCESS-NAME,ss-local,DIRECT
- PROCESS-NAME,privoxy,DIRECT
- PROCESS-NAME,leaf,DIRECT
- PROCESS-NAME,v2ray.exe,DIRECT
- PROCESS-NAME,xray.exe,DIRECT
- PROCESS-NAME,naive.exe,DIRECT
- PROCESS-NAME,trojan.exe,DIRECT
- PROCESS-NAME,trojan-go.exe,DIRECT
- PROCESS-NAME,ss-local.exe,DIRECT
- PROCESS-NAME,privoxy.exe,DIRECT
- PROCESS-NAME,leaf.exe,DIRECT
- PROCESS-NAME,Surge,DIRECT
- PROCESS-NAME,Surge 2,DIRECT
- PROCESS-NAME,Surge 3,DIRECT
- PROCESS-NAME,Surge 4,DIRECT
- PROCESS-NAME,Surge%202,DIRECT
- PROCESS-NAME,Surge%203,DIRECT
- PROCESS-NAME,Surge%204,DIRECT
- PROCESS-NAME,Thunder,DIRECT
- PROCESS-NAME,DownloadService,DIRECT
- PROCESS-NAME,qBittorrent,DIRECT
- PROCESS-NAME,Transmission,DIRECT
- PROCESS-NAME,fdm,DIRECT
- PROCESS-NAME,aria2c,DIRECT
- PROCESS-NAME,Folx,DIRECT
- PROCESS-NAME,NetTransport,DIRECT
- PROCESS-NAME,uTorrent,DIRECT
- PROCESS-NAME,WebTorrent,DIRECT
- PROCESS-NAME,aria2c.exe,DIRECT
- PROCESS-NAME,BitComet.exe,DIRECT
- PROCESS-NAME,fdm.exe,DIRECT
- PROCESS-NAME,NetTransport.exe,DIRECT
- PROCESS-NAME,qbittorrent.exe,DIRECT
- PROCESS-NAME,Thunder.exe,DIRECT
- PROCESS-NAME,ThunderVIP.exe,DIRECT
- PROCESS-NAME,transmission-daemon.exe,DIRECT
- PROCESS-NAME,transmission-qt.exe,DIRECT
- PROCESS-NAME,uTorrent.exe,DIRECT
- PROCESS-NAME,WebTorrent.exe,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- GEOIP,CN,DIRECT
- MATCH,PROXY
