port: 7890
socks-port: 1080 # SOCKS5代理端口，DNS请求会中转
redir-port: 3333 # 透明代理端口
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
secret: route

# 透明代理开启DNS
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: true # lookup hosts and return IP record
  nameserver:
  - tls://doh.pub:853   # DNSpod DoT
  - https://doh.pub/dns-query   # DNSpod DoH
  - 119.29.29.29   # DNSpod DNS 17ms
  # 提供 fallback 时，如果GEOIP非 CN 中国时使用 fallback 解析
  fallback:
  - tls://8.8.8.8:853   # Google DNS over TLS
  - tls://1.1.1.1:853   # cloudflare DNS over TLS
  - https://dns.google/dns-query   # Google DNS over HTTPS
  - https://cloudflare-dns.com/dns-query   # cloudflare DNS over HTTPS
  # 强制DNS解析使用`fallback`配置
  fallback-filter:
    # true: CN使用nameserver解析，非CN使用fallback
    geoip: true
    # geoip设置为false时有效： 不匹配`ipcidr`地址时会使用`nameserver`结果，匹配`ipcidr`地址时使用`fallback`结果。
    ipcidr:
    - 240.0.0.0/4


# 配置规则参考文档： https://github.com/Dreamacro/clash/wiki/configuration
# 设置代理提供者(远程订阅地址+本地订阅文件)
# proxy-providers:
#   provider_file:
#     type: file
#     path: ./provider_local.yaml
#     health-check:
#       enable: true
#       interval: 600
#       url: http://www.gstatic.com/generate_204
#   provider_url:
#     type: file
#     path: ./provider_remote.yaml
#     health-check:
#       enable: true
#       interval: 600
#       url: http://www.gstatic.com/generate_204
#
#
# DIY组保留的个人节点
proxies:
- name: 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:31572
  type: ss
  server: 198.147.22.87
  port: 31572
  cipher: aes-256-gcm
  password: n8w4StnbVD9dmXYn4Ajt87EA
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:31216
  type: ss
  server: 156.146.33.74
  port: 31216
  cipher: aes-256-gcm
  password: wJwXatAGZ8xX5K8C7mruf84x
- name: 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:40282
  type: ss
  server: 185.76.8.218
  port: 40282
  cipher: aes-256-gcm
  password: Pvvaw486867D2w4yctL2ULTQ
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:45948
  type: ss
  server: 198.8.92.84
  port: 45948
  cipher: aes-256-gcm
  password: j76EXqJcQhuQTr3EvUf7xaK9
- name: 🇷🇴罗马尼亚-布加勒斯特-0-ss-45.89.173.205:33992
  type: ss
  server: 45.89.173.205
  port: 33992
  cipher: aes-256-gcm
  password: 8n6pwAcrrv2pj6tFY2p3TbQ6
- name: 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:40093
  type: ss
  server: 198.147.22.87
  port: 40093
  cipher: aes-256-gcm
  password: x23Z4LGkGDkThZ9Kaz4DURQp
- name: 🇨🇦加拿大-安大略-多伦多-ss-198.57.27.218:8090
  type: ss
  server: 198.57.27.218
  port: 8090
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 🇺🇸美国-新泽西-0-ss-156.146.62.45:38747
  type: ss
  server: 156.146.62.45
  port: 38747
  cipher: aes-256-gcm
  password: RtbLkxbJZpUQ6m8y4qAeLYZj
- name: 🇨🇳中国-上海-上海-ss-101.91.121.247:50004
  type: ss
  server: 101.91.121.247
  port: 50004
  cipher: aes-256-cfb
  password: '4415934295'
- name: 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:47861
  type: ss
  server: 185.76.8.218
  port: 47861
  cipher: aes-256-gcm
  password: LJcChRsGQRhywrtXUU55TLTu
- name: 🇨🇳中国-香港-0-ss-118.107.244.110:5003
  type: ss
  server: 118.107.244.110
  port: 5003
  cipher: aes-256-gcm
  password: g5MeD6Ft3CWlJId
- name: 🇩🇪德国-黑森-0-ss-145.239.1.137:7307
  type: ss
  server: 145.239.1.137
  port: 7307
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:50168
  type: ss
  server: 185.76.8.218
  port: 50168
  cipher: aes-256-gcm
  password: WCuz7yrfZSCQQXSNrtGPz2HT
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:50181
  type: ss
  server: 156.146.33.74
  port: 50181
  cipher: aes-256-gcm
  password: d9adRr9UxymNSysYahMtpFpd
- name: 🇨🇳中国-香港-0-ss-118.107.244.110:7306
  type: ss
  server: 118.107.244.110
  port: 7306
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:49339
  type: ss
  server: 198.8.92.84
  port: 49339
  cipher: aes-256-gcm
  password: suucSeVLmt6PQKAP77NtGw9x
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:37588
  type: ss
  server: 198.8.92.84
  port: 37588
  cipher: aes-256-gcm
  password: kD9vkjnE6dsUzwQfvKkPkQAd
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:50168
  type: ss
  server: 198.8.92.84
  port: 50168
  cipher: aes-256-gcm
  password: WCuz7yrfZSCQQXSNrtGPz2HT
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:38747
  type: ss
  server: 156.146.33.74
  port: 38747
  cipher: aes-256-gcm
  password: RtbLkxbJZpUQ6m8y4qAeLYZj
- name: 🇸🇬新加坡-0-0-ss-51.79.166.171:50004
  type: ss
  server: 51.79.166.171
  port: 50004
  cipher: aes-256-cfb
  password: '4415934295'
- name: 🇨🇳中国-香港-0-ss-118.107.244.112:3306
  type: ss
  server: 118.107.244.112
  port: 3306
  cipher: aes-256-gcm
  password: Y6R9pAtvxxzmGC
- name: 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:34687
  type: ss
  server: 185.76.9.56
  port: 34687
  cipher: aes-256-gcm
  password: txmK9WhwP6WPhP7hqSBLVxpN
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:46726
  type: ss
  server: 156.146.33.74
  port: 46726
  cipher: aes-256-gcm
  password: 2fqKbFPGHpcmMTJzGsUbsfYf
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:31572
  type: ss
  server: 198.8.92.84
  port: 31572
  cipher: aes-256-gcm
  password: n8w4StnbVD9dmXYn4Ajt87EA
- name: 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:49126
  type: ss
  server: 185.76.8.218
  port: 49126
  cipher: aes-256-gcm
  password: wrCaGtrUbzeRqQLdc8Kmk3Nd
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:45948
  type: ss
  server: 156.146.33.74
  port: 45948
  cipher: aes-256-gcm
  password: j76EXqJcQhuQTr3EvUf7xaK9
- name: 🇨🇦加拿大-安大略-多伦多-ss-198.57.27.218:7306
  type: ss
  server: 198.57.27.218
  port: 7306
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 🇷🇴罗马尼亚-布加勒斯特-0-ss-37.120.235.69:38742
  type: ss
  server: 37.120.235.69
  port: 38742
  cipher: aes-256-gcm
  password: DKXfWwc4ebscpXTKpbt85rSH
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:44236
  type: ss
  server: 198.8.92.84
  port: 44236
  cipher: aes-256-gcm
  password: FWrXcxPZjJxAN89xLgqY3Acp
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:49653
  type: ss
  server: 198.8.92.84
  port: 49653
  cipher: aes-256-gcm
  password: Y9GcTPemHMKEkrfGQPJqFDNr
- name: 🇷🇴罗马尼亚-布加勒斯特-0-ss-45.89.173.205:33148
  type: ss
  server: 45.89.173.205
  port: 33148
  cipher: aes-256-gcm
  password: CMduaFXddcQbwNAAs7xFDnc8
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:33992
  type: ss
  server: 156.146.33.74
  port: 33992
  cipher: aes-256-gcm
  password: 8n6pwAcrrv2pj6tFY2p3TbQ6
- name: 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:42816
  type: ss
  server: 185.76.8.218
  port: 42816
  cipher: aes-256-gcm
  password: tBKBf4pVzNCFKdbPgvwrNXq3
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:48938
  type: ss
  server: 156.146.33.74
  port: 48938
  cipher: aes-256-gcm
  password: 4ejJ8n5ddLuYDUHGXJre2ufJ
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:37473
  type: ss
  server: 198.8.92.84
  port: 37473
  cipher: aes-256-gcm
  password: enctdKyJfSu76VqznKwTt6Ap
- name: 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:2376
  type: ss
  server: 46.29.218.6
  port: 2376
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:44102
  type: ss
  server: 156.146.33.74
  port: 44102
  cipher: aes-256-gcm
  password: zHKYS9DeAjvv43EwgDfyEg4d
- name: 🇨🇦加拿大-安大略-多伦多-ss-198.57.27.218:8091
  type: ss
  server: 198.57.27.218
  port: 8091
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:40711
  type: ss
  server: 156.146.33.74
  port: 40711
  cipher: aes-256-gcm
  password: rnngxSTJrXWKXHkvrF3npp9B
- name: 🇺🇸美国-加利福尼亚-费利蒙-ss-185.124.240.146:45329
  type: ss
  server: 185.124.240.146
  port: 45329
  cipher: aes-256-gcm
  password: CXSjgD7u7Ar7GxkZ4CgTMUsj
- name: 🇨🇳中国-香港-0-ss-118.107.244.110:3306
  type: ss
  server: 118.107.244.110
  port: 3306
  cipher: aes-256-gcm
  password: Y6R9pAtvxxzmGC
- name: 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:44742
  type: ss
  server: 185.76.8.218
  port: 44742
  cipher: aes-256-gcm
  password: QCStKzZ56SHBc4tL7stCEqqd
- name: 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:38620
  type: ss
  server: 185.76.8.218
  port: 38620
  cipher: aes-256-gcm
  password: Kquv5UhvZXNMemAQy8DxZ7qn
- name: 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:47027
  type: ss
  server: 185.76.8.218
  port: 47027
  cipher: aes-256-gcm
  password: Vt5pBJFwdtNB26cJbTXxm88Z
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:42304
  type: ss
  server: 198.8.92.84
  port: 42304
  cipher: aes-256-gcm
  password: p26v2JwhQVHDHsXk66fXt56r
- name: 🇳🇿新西兰-0-0-ss-107.150.94.12:41992
  type: ss
  server: 107.150.94.12
  port: 41992
  cipher: aes-256-gcm
  password: XmQSxDCn5ehpcq6DBYms8FJf
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:48794
  type: ss
  server: 198.8.92.84
  port: 48794
  cipher: aes-256-gcm
  password: r9Q3adc3ru9sfBDPEj4yp6U6
- name: 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:31764
  type: ss
  server: 185.76.8.218
  port: 31764
  cipher: aes-256-gcm
  password: YgusH2MWA8PWc3p2VDsR7AVv
- name: 🇨🇳中国-台湾-0-ssr-59.125.11.158:8158
  type: ssr
  server: 59.125.11.158
  password: passinfo123
  obfs: plain
  protocol: origin
  port: 8158
  cipher: rc4-md5
  protocol-param: ''
  obfs-param: ''

proxy-groups:
# 类型选择 简介
# select : 用于选择代理或代理组, 可以通过 RESTful API 来切换代理，建议在 GUI 中使用
# load-balance : 相同eTLD+1的请求将拨号到同一个代理。
# url-test : 通过对 URL 的速度进行基准测试来选择将使用哪个代理。
# fallback : 按优先级选择可用的策略。通过访问 URL 来测试可用性，就像自动 url-test 组一样。
# relay : 中继链接代理。代理不应包含中继。不支持 UDP。 流量：Clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet 
#  
# 推荐选择：
#   命令行服务建议选择 url-test / fallback / load-balance
#   GUI窗口 官方建议选择 select ，当然也推荐使用url-test 自动检测可用性。
- name: PROXY
  type: select   # load-balance, select, relay, fallback, url-test
  tolerance: 300
    # lazy: true
  url: http://www.gstatic.com/generate_204
  interval: 300
    # strategy: consistent-hashing # or round-robin  # 负载均衡策略
  proxies:
  - 🇺🇸美国-新泽西-0-ss-156.146.62.45:38747
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:50181
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:48938
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:46726
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:45948
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:44102
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:40711
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:38747
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:33992
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:31216
  - 🇺🇸美国-加利福尼亚-费利蒙-ss-185.124.240.146:45329
  - 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:40093
  - 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:31572
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:50168
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:49653
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:49339
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:48794
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:45948
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:44236
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:42304
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:37588
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:37473
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:31572
  - 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:50168
  - 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:49126
  - 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:47861
  - 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:47027
  - 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:44742
  - 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:42816
  - 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:40282
  - 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:38620
  - 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:31764
  - 🇸🇬新加坡-0-0-ss-51.79.166.171:50004
  - 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:34687
  - 🇷🇴罗马尼亚-布加勒斯特-0-ss-45.89.173.205:33992
  - 🇷🇴罗马尼亚-布加勒斯特-0-ss-45.89.173.205:33148
  - 🇷🇴罗马尼亚-布加勒斯特-0-ss-37.120.235.69:38742
  - 🇳🇿新西兰-0-0-ss-107.150.94.12:41992
  - 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:2376
  - 🇩🇪德国-黑森-0-ss-145.239.1.137:7307
  - 🇨🇳中国-香港-0-ss-118.107.244.112:3306
  - 🇨🇳中国-香港-0-ss-118.107.244.110:7306
  - 🇨🇳中国-香港-0-ss-118.107.244.110:5003
  - 🇨🇳中国-香港-0-ss-118.107.244.110:3306
  - 🇨🇳中国-台湾-0-ssr-59.125.11.158:8158
  - 🇨🇳中国-上海-上海-ss-101.91.121.247:50004
  - 🇨🇦加拿大-安大略-多伦多-ss-198.57.27.218:8091
  - 🇨🇦加拿大-安大略-多伦多-ss-198.57.27.218:8090
  - 🇨🇦加拿大-安大略-多伦多-ss-198.57.27.218:7306
rules:
  # 黑名单模式，命中规则使用代理
- PROCESS-NAME,v2ray,DIRECT
- PROCESS-NAME,xray,DIRECT
- PROCESS-NAME,naive,DIRECT
- PROCESS-NAME,trojan,DIRECT
- PROCESS-NAME,trojan-go,DIRECT
- PROCESS-NAME,ss-local,DIRECT
- PROCESS-NAME,privoxy,DIRECT
- PROCESS-NAME,leaf,DIRECT
- PROCESS-NAME,v2ray.exe,DIRECT
- PROCESS-NAME,xray.exe,DIRECT
- PROCESS-NAME,naive.exe,DIRECT
- PROCESS-NAME,trojan.exe,DIRECT
- PROCESS-NAME,trojan-go.exe,DIRECT
- PROCESS-NAME,ss-local.exe,DIRECT
- PROCESS-NAME,privoxy.exe,DIRECT
- PROCESS-NAME,leaf.exe,DIRECT
- PROCESS-NAME,Surge,DIRECT
- PROCESS-NAME,Surge 2,DIRECT
- PROCESS-NAME,Surge 3,DIRECT
- PROCESS-NAME,Surge 4,DIRECT
- PROCESS-NAME,Surge%202,DIRECT
- PROCESS-NAME,Surge%203,DIRECT
- PROCESS-NAME,Surge%204,DIRECT
- PROCESS-NAME,Thunder,DIRECT
- PROCESS-NAME,DownloadService,DIRECT
- PROCESS-NAME,qBittorrent,DIRECT
- PROCESS-NAME,Transmission,DIRECT
- PROCESS-NAME,fdm,DIRECT
- PROCESS-NAME,aria2c,DIRECT
- PROCESS-NAME,Folx,DIRECT
- PROCESS-NAME,NetTransport,DIRECT
- PROCESS-NAME,uTorrent,DIRECT
- PROCESS-NAME,WebTorrent,DIRECT
- PROCESS-NAME,aria2c.exe,DIRECT
- PROCESS-NAME,BitComet.exe,DIRECT
- PROCESS-NAME,fdm.exe,DIRECT
- PROCESS-NAME,NetTransport.exe,DIRECT
- PROCESS-NAME,qbittorrent.exe,DIRECT
- PROCESS-NAME,Thunder.exe,DIRECT
- PROCESS-NAME,ThunderVIP.exe,DIRECT
- PROCESS-NAME,transmission-daemon.exe,DIRECT
- PROCESS-NAME,transmission-qt.exe,DIRECT
- PROCESS-NAME,uTorrent.exe,DIRECT
- PROCESS-NAME,WebTorrent.exe,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- GEOIP,CN,DIRECT
- MATCH,PROXY
