port: 7890
socks-port: 1080 # SOCKS5代理端口，DNS请求会中转
redir-port: 3333 # 透明代理端口
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
secret: route

# 透明代理开启DNS
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: true # lookup hosts and return IP record
  nameserver:
  - tls://doh.pub:853   # DNSpod DoT
  - https://doh.pub/dns-query   # DNSpod DoH
  - 119.29.29.29   # DNSpod DNS 17ms
  # 提供 fallback 时，如果GEOIP非 CN 中国时使用 fallback 解析
  fallback:
  - tls://8.8.8.8:853   # Google DNS over TLS
  - tls://1.1.1.1:853   # cloudflare DNS over TLS
  - https://dns.google/dns-query   # Google DNS over HTTPS
  - https://cloudflare-dns.com/dns-query   # cloudflare DNS over HTTPS
  # 强制DNS解析使用`fallback`配置
  fallback-filter:
    # true: CN使用nameserver解析，非CN使用fallback
    geoip: true
    # geoip设置为false时有效： 不匹配`ipcidr`地址时会使用`nameserver`结果，匹配`ipcidr`地址时使用`fallback`结果。
    ipcidr:
    - 240.0.0.0/4


# 配置规则参考文档： https://github.com/Dreamacro/clash/wiki/configuration
# 设置代理提供者(远程订阅地址+本地订阅文件)
# proxy-providers:
#   provider_file:
#     type: file
#     path: ./provider_local.yaml
#     health-check:
#       enable: true
#       interval: 600
#       url: http://www.gstatic.com/generate_204
#   provider_url:
#     type: file
#     path: ./provider_remote.yaml
#     health-check:
#       enable: true
#       interval: 600
#       url: http://www.gstatic.com/generate_204
#
#
# DIY组保留的个人节点
proxies:
- name: 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:31572
  type: ss
  server: 185.76.8.218
  port: 31572
  cipher: aes-256-gcm
  password: n8w4StnbVD9dmXYn4Ajt87EA
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:42166
  type: ss
  server: 156.146.33.74
  port: 42166
  cipher: aes-256-gcm
  password: H9Dbn3szZMqLR3NpgEFEPCKb
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:40093
  type: ss
  server: 198.8.92.84
  port: 40093
  cipher: aes-256-gcm
  password: x23Z4LGkGDkThZ9Kaz4DURQp
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:44945
  type: ss
  server: 198.8.92.84
  port: 44945
  cipher: aes-256-gcm
  password: F5bKkb9ggkLx4JbQrbLn7LjZ
- name: 欧洲-0-0-ss-138.199.42.170:49396
  type: ss
  server: 138.199.42.170
  port: 49396
  cipher: aes-256-gcm
  password: BdRWC38L5JUDMTYNNxJGcUwB
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:49653
  type: ss
  server: 198.8.92.84
  port: 49653
  cipher: aes-256-gcm
  password: Y9GcTPemHMKEkrfGQPJqFDNr
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:48794
  type: ss
  server: 198.8.92.84
  port: 48794
  cipher: aes-256-gcm
  password: r9Q3adc3ru9sfBDPEj4yp6U6
- name: 🇳🇿新西兰-0-0-ss-107.150.94.14:44539
  type: ss
  server: 107.150.94.14
  port: 44539
  cipher: aes-256-gcm
  password: r6hDrkP4Et6EENTS8Qy7Tcmg
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:35294
  type: ss
  server: 198.8.92.84
  port: 35294
  cipher: aes-256-gcm
  password: J9Y2ncrdPEC38gwydNFFGBna
- name: 🇨🇳中国-香港-0-ss-118.107.244.110:5003
  type: ss
  server: 118.107.244.110
  port: 5003
  cipher: aes-256-gcm
  password: g5MeD6Ft3CWlJId
- name: 🇨🇳中国-香港-0-ss-118.107.244.110:3389
  type: ss
  server: 118.107.244.110
  port: 3389
  cipher: aes-256-gcm
  password: Y6R9pAtvxxzmGC
- name: 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:2375
  type: ss
  server: 46.29.218.6
  port: 2375
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:48938
  type: ss
  server: 185.76.9.56
  port: 48938
  cipher: aes-256-gcm
  password: 4ejJ8n5ddLuYDUHGXJre2ufJ
- name: 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:443
  type: ss
  server: 46.29.218.6
  port: 443
  cipher: aes-256-gcm
  password: pKEW8JPByTVTLtM
- name: 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:7306
  type: ss
  server: 46.29.218.6
  port: 7306
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:31572
  type: ss
  server: 198.8.92.84
  port: 31572
  cipher: aes-256-gcm
  password: n8w4StnbVD9dmXYn4Ajt87EA
- name: 🇨🇦加拿大-安大略-多伦多-ss-198.57.27.218:8091
  type: ss
  server: 198.57.27.218
  port: 8091
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 🇨🇳中国-香港-0-ss-118.107.244.110:7307
  type: ss
  server: 118.107.244.110
  port: 7307
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:49396
  type: ss
  server: 156.146.33.74
  port: 49396
  cipher: aes-256-gcm
  password: BdRWC38L5JUDMTYNNxJGcUwB
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:49468
  type: ss
  server: 156.146.33.74
  port: 49468
  cipher: aes-256-gcm
  password: LsYSQDxmPj9AcWpSX5HrYfu6
- name: 🇳🇿新西兰-0-0-ss-107.150.94.12:38620
  type: ss
  server: 107.150.94.12
  port: 38620
  cipher: aes-256-gcm
  password: Kquv5UhvZXNMemAQy8DxZ7qn
- name: 🇩🇰丹麦-0-0-ss-185.108.106.175:42304
  type: ss
  server: 185.108.106.175
  port: 42304
  cipher: aes-256-gcm
  password: p26v2JwhQVHDHsXk66fXt56r
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:48089
  type: ss
  server: 156.146.33.74
  port: 48089
  cipher: aes-256-gcm
  password: apqQgXJyVDsdJMAYV4xspRFK
- name: 🇩🇪德国-黑森-0-ss-145.239.1.137:2376
  type: ss
  server: 145.239.1.137
  port: 2376
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:41372
  type: ss
  server: 198.8.92.84
  port: 41372
  cipher: aes-256-gcm
  password: 5kGAhC3AmVC35GbruHjSrZf2
- name: 🇷🇴罗马尼亚-布加勒斯特-0-ss-45.89.173.205:33148
  type: ss
  server: 45.89.173.205
  port: 33148
  cipher: aes-256-gcm
  password: CMduaFXddcQbwNAAs7xFDnc8
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:40711
  type: ss
  server: 156.146.33.74
  port: 40711
  cipher: aes-256-gcm
  password: rnngxSTJrXWKXHkvrF3npp9B
- name: 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:8090
  type: ss
  server: 46.29.218.6
  port: 8090
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:33992
  type: ss
  server: 198.147.22.87
  port: 33992
  cipher: aes-256-gcm
  password: 8n6pwAcrrv2pj6tFY2p3TbQ6
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:45746
  type: ss
  server: 198.8.92.84
  port: 45746
  cipher: aes-256-gcm
  password: wEsFcHCvbL4eJkL4DZQa7RgR
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:49719
  type: ss
  server: 156.146.33.74
  port: 49719
  cipher: aes-256-gcm
  password: 42SjT9vBF6ma9eFF3URaJpQ4
- name: 🇩🇪德国-黑森-0-ss-145.239.1.137:8090
  type: ss
  server: 145.239.1.137
  port: 8090
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:38747
  type: ss
  server: 156.146.33.74
  port: 38747
  cipher: aes-256-gcm
  password: RtbLkxbJZpUQ6m8y4qAeLYZj
- name: 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:48794
  type: ss
  server: 185.76.9.56
  port: 48794
  cipher: aes-256-gcm
  password: r9Q3adc3ru9sfBDPEj4yp6U6
- name: 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:44742
  type: ss
  server: 185.76.8.218
  port: 44742
  cipher: aes-256-gcm
  password: QCStKzZ56SHBc4tL7stCEqqd
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:41306
  type: ss
  server: 156.146.33.74
  port: 41306
  cipher: aes-256-gcm
  password: pzB5Y2twNtqFzWhEbBsPJMjj
- name: 🇨🇳中国-香港-0-ss-118.107.244.110:3306
  type: ss
  server: 118.107.244.110
  port: 3306
  cipher: aes-256-gcm
  password: Y6R9pAtvxxzmGC
- name: 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:33998
  type: ss
  server: 198.147.22.87
  port: 33998
  cipher: aes-256-gcm
  password: NHwQTPLCfaTMSqTnU3mjcSxe
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:46726
  type: ss
  server: 198.8.92.84
  port: 46726
  cipher: aes-256-gcm
  password: 2fqKbFPGHpcmMTJzGsUbsfYf
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:37559
  type: ss
  server: 198.8.92.84
  port: 37559
  cipher: aes-256-gcm
  password: Qbt22F6JsxzFGqcsK5SaR8q3
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:32843
  type: ss
  server: 156.146.33.74
  port: 32843
  cipher: aes-256-gcm
  password: G35YSR2LFNEM9bq2dkjmKQRr
- name: 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:31572
  type: ss
  server: 198.147.22.87
  port: 31572
  cipher: aes-256-gcm
  password: n8w4StnbVD9dmXYn4Ajt87EA
- name: 🇩🇪德国-黑森-0-ss-145.239.1.137:7307
  type: ss
  server: 145.239.1.137
  port: 7307
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 🇳🇿新西兰-0-0-ss-107.150.94.12:31572
  type: ss
  server: 107.150.94.12
  port: 31572
  cipher: aes-256-gcm
  password: n8w4StnbVD9dmXYn4Ajt87EA
- name: 🇩🇪德国-法兰克福-法兰克福-ss-172.105.251.193:2376
  type: ss
  server: 172.105.251.193
  port: 2376
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:39772
  type: ss
  server: 198.147.22.87
  port: 39772
  cipher: aes-256-gcm
  password: CUndSZnYsPKcu6Kj8THVMBHD
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:38747
  type: ss
  server: 2.58.241.133
  port: 38747
  cipher: aes-256-gcm
  password: RtbLkxbJZpUQ6m8y4qAeLYZj
- name: 🇨🇳中国-福建-泉州-ssr-117.28.243.132:8333
  type: ssr
  server: 117.28.243.132
  password: passfw2xs4e!
  obfs: plain
  protocol: origin
  port: 8333
  cipher: rc4-md5
  protocol-param: ''
  obfs-param: ''
- name: 🇨🇳中国-福建-泉州-ssr-117.28.243.169:8333
  type: ssr
  server: 117.28.243.169
  password: passfw2xs4e!
  obfs: plain
  protocol: origin
  port: 8333
  cipher: rc4-md5
  protocol-param: ''
  obfs-param: ''
- name: 🇯🇵日本-东京都-东京-v2ray-54.238.161.11:80
  type: vmess
  server: 54.238.161.11
  network: ws
  port: 80
  uuid: 261aeb5f-b6f7-359c-a321-9794bf344e12
  alterId: 4
  cipher: auto
  tls: false
  ws-path: /v2ray
- name: 🇺🇸美国-加利福尼亚-0-v2ray-45.32.74.58:43320
  type: vmess
  server: 45.32.74.58
  network: ws
  port: 43320
  uuid: 207f01a0-4621-11ec-8b00-560003ae8b46
  alterId: 4
  cipher: auto
  tls: false
  ws-path: /hZqt4s9f/
- name: 🇺🇸美国-德克萨斯-0-v2ray-159.223.75.43:56776
  type: vmess
  server: 159.223.75.43
  network: ws
  port: 56776
  uuid: 2a1620a3-dc12-4d2e-faa9-809028d3e191
  alterId: 4
  cipher: auto
  tls: false
  ws-path: /

proxy-groups:
# 类型选择 简介
# select : 用于选择代理或代理组, 可以通过 RESTful API 来切换代理，建议在 GUI 中使用
# load-balance : 相同eTLD+1的请求将拨号到同一个代理。
# url-test : 通过对 URL 的速度进行基准测试来选择将使用哪个代理。
# fallback : 按优先级选择可用的策略。通过访问 URL 来测试可用性，就像自动 url-test 组一样。
# relay : 中继链接代理。代理不应包含中继。不支持 UDP。 流量：Clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet 
#  
# 推荐选择：
#   命令行服务建议选择 url-test / fallback / load-balance
#   GUI窗口 官方建议选择 select ，当然也推荐使用url-test 自动检测可用性。
- name: PROXY
  type: select   # load-balance, select, relay, fallback, url-test
  tolerance: 300
    # lazy: true
  url: http://www.gstatic.com/generate_204
  interval: 300
    # strategy: consistent-hashing # or round-robin  # 负载均衡策略
  proxies:
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:49719
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:49468
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:49396
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:48089
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:42166
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:41306
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:40711
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:38747
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:32843
  - 🇺🇸美国-德克萨斯-0-v2ray-159.223.75.43:56776
  - 🇺🇸美国-加利福尼亚-0-v2ray-45.32.74.58:43320
  - 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:39772
  - 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:33998
  - 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:33992
  - 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:31572
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:49653
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:48794
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:46726
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:45746
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:44945
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:41372
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:40093
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:37559
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:35294
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:31572
  - 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:44742
  - 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:31572
  - 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:48938
  - 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:48794
  - 🇷🇴罗马尼亚-布加勒斯特-0-ss-45.89.173.205:33148
  - 🇳🇿新西兰-0-0-ss-107.150.94.14:44539
  - 🇳🇿新西兰-0-0-ss-107.150.94.12:38620
  - 🇳🇿新西兰-0-0-ss-107.150.94.12:31572
  - 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:8090
  - 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:7306
  - 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:443
  - 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:2375
  - 🇯🇵日本-东京都-东京-v2ray-54.238.161.11:80
  - 🇩🇰丹麦-0-0-ss-185.108.106.175:42304
  - 🇩🇪德国-黑森-0-ss-145.239.1.137:8090
  - 🇩🇪德国-黑森-0-ss-145.239.1.137:7307
  - 🇩🇪德国-黑森-0-ss-145.239.1.137:2376
  - 🇩🇪德国-法兰克福-法兰克福-ss-172.105.251.193:2376
  - 🇨🇳中国-香港-0-ss-118.107.244.110:7307
  - 🇨🇳中国-香港-0-ss-118.107.244.110:5003
  - 🇨🇳中国-香港-0-ss-118.107.244.110:3389
  - 🇨🇳中国-香港-0-ss-118.107.244.110:3306
  - 🇨🇳中国-福建-泉州-ssr-117.28.243.169:8333
  - 🇨🇳中国-福建-泉州-ssr-117.28.243.132:8333
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:38747
  - 🇨🇦加拿大-安大略-多伦多-ss-198.57.27.218:8091
  - 欧洲-0-0-ss-138.199.42.170:49396
rules:
  # 黑名单模式，命中规则使用代理
- PROCESS-NAME,v2ray,DIRECT
- PROCESS-NAME,xray,DIRECT
- PROCESS-NAME,naive,DIRECT
- PROCESS-NAME,trojan,DIRECT
- PROCESS-NAME,trojan-go,DIRECT
- PROCESS-NAME,ss-local,DIRECT
- PROCESS-NAME,privoxy,DIRECT
- PROCESS-NAME,leaf,DIRECT
- PROCESS-NAME,v2ray.exe,DIRECT
- PROCESS-NAME,xray.exe,DIRECT
- PROCESS-NAME,naive.exe,DIRECT
- PROCESS-NAME,trojan.exe,DIRECT
- PROCESS-NAME,trojan-go.exe,DIRECT
- PROCESS-NAME,ss-local.exe,DIRECT
- PROCESS-NAME,privoxy.exe,DIRECT
- PROCESS-NAME,leaf.exe,DIRECT
- PROCESS-NAME,Surge,DIRECT
- PROCESS-NAME,Surge 2,DIRECT
- PROCESS-NAME,Surge 3,DIRECT
- PROCESS-NAME,Surge 4,DIRECT
- PROCESS-NAME,Surge%202,DIRECT
- PROCESS-NAME,Surge%203,DIRECT
- PROCESS-NAME,Surge%204,DIRECT
- PROCESS-NAME,Thunder,DIRECT
- PROCESS-NAME,DownloadService,DIRECT
- PROCESS-NAME,qBittorrent,DIRECT
- PROCESS-NAME,Transmission,DIRECT
- PROCESS-NAME,fdm,DIRECT
- PROCESS-NAME,aria2c,DIRECT
- PROCESS-NAME,Folx,DIRECT
- PROCESS-NAME,NetTransport,DIRECT
- PROCESS-NAME,uTorrent,DIRECT
- PROCESS-NAME,WebTorrent,DIRECT
- PROCESS-NAME,aria2c.exe,DIRECT
- PROCESS-NAME,BitComet.exe,DIRECT
- PROCESS-NAME,fdm.exe,DIRECT
- PROCESS-NAME,NetTransport.exe,DIRECT
- PROCESS-NAME,qbittorrent.exe,DIRECT
- PROCESS-NAME,Thunder.exe,DIRECT
- PROCESS-NAME,ThunderVIP.exe,DIRECT
- PROCESS-NAME,transmission-daemon.exe,DIRECT
- PROCESS-NAME,transmission-qt.exe,DIRECT
- PROCESS-NAME,uTorrent.exe,DIRECT
- PROCESS-NAME,WebTorrent.exe,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- GEOIP,CN,DIRECT
- MATCH,PROXY
