port: 7890
socks-port: 1080 # SOCKS5代理端口，DNS请求会中转
redir-port: 3333 # 透明代理端口
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
secret: route

# 透明代理开启DNS
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: true # lookup hosts and return IP record
  nameserver:
  - tls://doh.pub:853   # DNSpod DoT
  - https://doh.pub/dns-query   # DNSpod DoH
  - 119.29.29.29   # DNSpod DNS 17ms
  # 提供 fallback 时，如果GEOIP非 CN 中国时使用 fallback 解析
  fallback:
  - tls://8.8.8.8:853   # Google DNS over TLS
  - tls://1.1.1.1:853   # cloudflare DNS over TLS
  - https://dns.google/dns-query   # Google DNS over HTTPS
  - https://cloudflare-dns.com/dns-query   # cloudflare DNS over HTTPS
  # 强制DNS解析使用`fallback`配置
  fallback-filter:
    # true: CN使用nameserver解析，非CN使用fallback
    geoip: true
    # geoip设置为false时有效： 不匹配`ipcidr`地址时会使用`nameserver`结果，匹配`ipcidr`地址时使用`fallback`结果。
    ipcidr:
    - 240.0.0.0/4


# 配置规则参考文档： https://github.com/Dreamacro/clash/wiki/configuration
# 设置代理提供者(远程订阅地址+本地订阅文件)
# proxy-providers:
#   provider_file:
#     type: file
#     path: ./provider_local.yaml
#     health-check:
#       enable: true
#       interval: 600
#       url: http://www.gstatic.com/generate_204
#   provider_url:
#     type: file
#     path: ./provider_remote.yaml
#     health-check:
#       enable: true
#       interval: 600
#       url: http://www.gstatic.com/generate_204
#
#
# DIY组保留的个人节点
proxies:
- name: 🇮🇹意大利-米兰-米兰-ss-212.102.54.163:41738
  type: ss
  server: 212.102.54.163
  port: 41738
  cipher: aes-256-gcm
  password: X6yMGXnfUsuKTvEDYZSLPk4d
- name: 🇨🇳中国-上海-上海-ss-101.91.121.247:50004
  type: ss
  server: 101.91.121.247
  port: 50004
  cipher: aes-256-cfb
  password: '4415934295'
- name: 🇩🇪德国-法兰克福-法兰克福-ss-172.105.251.193:2376
  type: ss
  server: 172.105.251.193
  port: 2376
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:39171
  type: ss
  server: 156.146.33.74
  port: 39171
  cipher: aes-256-gcm
  password: z4pM2gA9QEEC6NRmqTQubm6Z
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:31572
  type: ss
  server: 156.146.33.74
  port: 31572
  cipher: aes-256-gcm
  password: n8w4StnbVD9dmXYn4Ajt87EA
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:38620
  type: ss
  server: 156.146.33.74
  port: 38620
  cipher: aes-256-gcm
  password: Kquv5UhvZXNMemAQy8DxZ7qn
- name: 🇯🇵日本-东京都-东京-ss-89.187.161.4:39772
  type: ss
  server: 89.187.161.4
  port: 39772
  cipher: aes-256-gcm
  password: CUndSZnYsPKcu6Kj8THVMBHD
- name: 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:2375
  type: ss
  server: 46.29.218.6
  port: 2375
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:47553
  type: ss
  server: 156.146.33.74
  port: 47553
  cipher: aes-256-gcm
  password: t2JnnFqjDMmzWurseJPgBsYY
- name: 🇮🇹意大利-米兰-米兰-ss-212.102.54.161:42304
  type: ss
  server: 212.102.54.161
  port: 42304
  cipher: aes-256-gcm
  password: p26v2JwhQVHDHsXk66fXt56r
- name: 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:33992
  type: ss
  server: 198.147.22.87
  port: 33992
  cipher: aes-256-gcm
  password: 8n6pwAcrrv2pj6tFY2p3TbQ6
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:40711
  type: ss
  server: 156.146.33.74
  port: 40711
  cipher: aes-256-gcm
  password: rnngxSTJrXWKXHkvrF3npp9B
- name: 🇳🇿新西兰-0-0-ss-107.150.94.12:31572
  type: ss
  server: 107.150.94.12
  port: 31572
  cipher: aes-256-gcm
  password: n8w4StnbVD9dmXYn4Ajt87EA
- name: 🇩🇰丹麦-0-0-ss-185.108.106.172:42816
  type: ss
  server: 185.108.106.172
  port: 42816
  cipher: aes-256-gcm
  password: tBKBf4pVzNCFKdbPgvwrNXq3
- name: 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:8091
  type: ss
  server: 46.29.218.6
  port: 8091
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:47861
  type: ss
  server: 156.146.33.74
  port: 47861
  cipher: aes-256-gcm
  password: LJcChRsGQRhywrtXUU55TLTu
- name: 🇮🇹意大利-米兰-米兰-ss-212.102.54.161:40282
  type: ss
  server: 212.102.54.161
  port: 40282
  cipher: aes-256-gcm
  password: Pvvaw486867D2w4yctL2ULTQ
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:49719
  type: ss
  server: 156.146.33.74
  port: 49719
  cipher: aes-256-gcm
  password: 42SjT9vBF6ma9eFF3URaJpQ4
- name: 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:44742
  type: ss
  server: 185.76.9.56
  port: 44742
  cipher: aes-256-gcm
  password: QCStKzZ56SHBc4tL7stCEqqd
- name: 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:2376
  type: ss
  server: 46.29.218.6
  port: 2376
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:46726
  type: ss
  server: 185.76.9.56
  port: 46726
  cipher: aes-256-gcm
  password: 2fqKbFPGHpcmMTJzGsUbsfYf
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:41306
  type: ss
  server: 156.146.33.74
  port: 41306
  cipher: aes-256-gcm
  password: pzB5Y2twNtqFzWhEbBsPJMjj
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:48089
  type: ss
  server: 156.146.33.74
  port: 48089
  cipher: aes-256-gcm
  password: apqQgXJyVDsdJMAYV4xspRFK
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:32843
  type: ss
  server: 156.146.33.74
  port: 32843
  cipher: aes-256-gcm
  password: G35YSR2LFNEM9bq2dkjmKQRr
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:31764
  type: ss
  server: 156.146.33.74
  port: 31764
  cipher: aes-256-gcm
  password: YgusH2MWA8PWc3p2VDsR7AVv
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:48794
  type: ss
  server: 156.146.33.74
  port: 48794
  cipher: aes-256-gcm
  password: r9Q3adc3ru9sfBDPEj4yp6U6
- name: 🇯🇵日本-东京都-东京-ss-89.187.161.4:40093
  type: ss
  server: 89.187.161.4
  port: 40093
  cipher: aes-256-gcm
  password: x23Z4LGkGDkThZ9Kaz4DURQp
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:45948
  type: ss
  server: 156.146.33.74
  port: 45948
  cipher: aes-256-gcm
  password: j76EXqJcQhuQTr3EvUf7xaK9
- name: 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:44102
  type: ss
  server: 185.76.9.56
  port: 44102
  cipher: aes-256-gcm
  password: zHKYS9DeAjvv43EwgDfyEg4d
- name: 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:36460
  type: ss
  server: 185.76.9.56
  port: 36460
  cipher: aes-256-gcm
  password: yUXad7DGF8L5cTShEpnp2N6z
- name: 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:47121
  type: ss
  server: 185.76.9.56
  port: 47121
  cipher: aes-256-gcm
  password: CTK8GXFQgKYQErrghPJfZ6tk
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:32558
  type: ss
  server: 156.146.33.74
  port: 32558
  cipher: aes-256-gcm
  password: gJYzm3TLbdL495ryQptaJXQk
- name: 🇮🇹意大利-米兰-米兰-ss-212.102.54.161:33998
  type: ss
  server: 212.102.54.161
  port: 33998
  cipher: aes-256-gcm
  password: NHwQTPLCfaTMSqTnU3mjcSxe
- name: 🇮🇹意大利-米兰-米兰-ss-212.102.54.163:44820
  type: ss
  server: 212.102.54.163
  port: 44820
  cipher: aes-256-gcm
  password: jspgz9G3VmvBMCgMUWLBaZHu
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:38747
  type: ss
  server: 156.146.33.74
  port: 38747
  cipher: aes-256-gcm
  password: RtbLkxbJZpUQ6m8y4qAeLYZj
- name: 🇳🇿新西兰-0-0-ss-107.150.94.12:38620
  type: ss
  server: 107.150.94.12
  port: 38620
  cipher: aes-256-gcm
  password: Kquv5UhvZXNMemAQy8DxZ7qn
- name: 🇵🇱波兰-华沙-0-ss-5.253.206.229:40093
  type: ss
  server: 5.253.206.229
  port: 40093
  cipher: aes-256-gcm
  password: x23Z4LGkGDkThZ9Kaz4DURQp
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.66:38620
  type: ss
  server: 156.146.33.66
  port: 38620
  cipher: aes-256-gcm
  password: Kquv5UhvZXNMemAQy8DxZ7qn
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.66:34687
  type: ss
  server: 156.146.33.66
  port: 34687
  cipher: aes-256-gcm
  password: txmK9WhwP6WPhP7hqSBLVxpN
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.66:49126
  type: ss
  server: 156.146.33.66
  port: 49126
  cipher: aes-256-gcm
  password: wrCaGtrUbzeRqQLdc8Kmk3Nd
- name: 🇩🇰丹麦-0-0-ss-185.108.106.175:41992
  type: ss
  server: 185.108.106.175
  port: 41992
  cipher: aes-256-gcm
  password: XmQSxDCn5ehpcq6DBYms8FJf
- name: 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:443
  type: ss
  server: 46.29.218.6
  port: 443
  cipher: aes-256-gcm
  password: pKEW8JPByTVTLtM
- name: 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:31572
  type: ss
  server: 198.147.22.87
  port: 31572
  cipher: aes-256-gcm
  password: n8w4StnbVD9dmXYn4Ajt87EA
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:49468
  type: ss
  server: 156.146.33.74
  port: 49468
  cipher: aes-256-gcm
  password: LsYSQDxmPj9AcWpSX5HrYfu6
- name: 🇮🇹意大利-米兰-米兰-ss-212.102.54.163:47861
  type: ss
  server: 212.102.54.163
  port: 47861
  cipher: aes-256-gcm
  password: LJcChRsGQRhywrtXUU55TLTu
- name: 🇨🇦加拿大-安大略-多伦多-ss-198.57.27.218:8090
  type: ss
  server: 198.57.27.218
  port: 8090
  cipher: aes-256-gcm
  password: PCnnH6SQSnfoS27
- name: 🇨🇳中国-福建-泉州-ss-117.28.243.132:8333
  type: ss
  server: 117.28.243.132
  port: 8333
  cipher: rc4-md5
  password: passfw2xs4e!
- name: 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:39772
  type: ss
  server: 198.147.22.87
  port: 39772
  cipher: aes-256-gcm
  password: CUndSZnYsPKcu6Kj8THVMBHD
- name: 🇨🇳中国-福建-泉州-ssr-117.28.243.132:8333
  type: ssr
  server: 117.28.243.132
  password: passfw2xs4e!
  obfs: plain
  protocol: origin
  port: 8333
  cipher: rc4-md5
  protocol-param: ''
  obfs-param: ''
- name: 🇯🇵日本-东京都-东京-v2ray-54.238.161.11:80
  type: vmess
  server: 54.238.161.11
  network: ws
  port: 80
  uuid: 261aeb5f-b6f7-359c-a321-9794bf344e12
  alterId: 4
  cipher: auto
  tls: false
  ws-path: /v2ray
- name: 🇺🇸美国-0-0-v2ray-18.162.214.245:8888
  type: vmess
  server: 18.162.214.245
  network: ws
  port: 8888
  uuid: 261aeb5f-b6f7-359c-a321-9794bf344e12
  alterId: 4
  cipher: auto
  tls: false
  ws-path: /v2ray
- name: 🇰🇷韩国-首尔-首尔-v2ray-3.38.95.113:1234
  type: vmess
  server: 3.38.95.113
  network: ws
  port: 1234
  uuid: 261aeb5f-b6f7-359c-a321-9794bf344e12
  alterId: 4
  cipher: auto
  tls: false
  ws-path: /v2ray
- name: 🇷🇺俄罗斯-Novosibirskaya-0-v2ray-91.206.92.27:55183
  type: vmess
  server: 91.206.92.27
  network: ws
  port: 55183
  uuid: ff282966-445c-11ec-999f-be23af0dedfd
  alterId: 4
  cipher: auto
  tls: false
  ws-path: /sjSiPE65/
- name: 🇸🇬新加坡-0-0-v2ray-139.59.254.17:12081
  type: vmess
  server: 139.59.254.17
  network: ws
  port: 12081
  uuid: 39f1943b-282e-44a4-9f56-5d59107d919e
  alterId: 4
  cipher: auto
  tls: false
  ws-path: /
- name: 🇸🇬新加坡-0-0-v2ray-139.59.122.24:34715
  type: vmess
  server: 139.59.122.24
  network: ws
  port: 34715
  uuid: 28eeec13-db80-4cb9-9d30-060f4257d729
  alterId: 4
  cipher: auto
  tls: false
  ws-path: /
- name: 🇺🇸美国-科罗拉多-0-v2ray-143.198.237.214:27489
  type: vmess
  server: 143.198.237.214
  network: ws
  port: 27489
  uuid: d73f027b-9a37-4e79-dd29-3a0d1e1da128
  alterId: 4
  cipher: auto
  tls: false
  ws-path: /

proxy-groups:
# 类型选择 简介
# select : 用于选择代理或代理组, 可以通过 RESTful API 来切换代理，建议在 GUI 中使用
# load-balance : 相同eTLD+1的请求将拨号到同一个代理。
# url-test : 通过对 URL 的速度进行基准测试来选择将使用哪个代理。
# fallback : 按优先级选择可用的策略。通过访问 URL 来测试可用性，就像自动 url-test 组一样。
# relay : 中继链接代理。代理不应包含中继。不支持 UDP。 流量：Clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet 
#  
# 推荐选择：
#   命令行服务建议选择 url-test / fallback / load-balance
#   GUI窗口 官方建议选择 select ，当然也推荐使用url-test 自动检测可用性。
- name: PROXY
  type: select   # load-balance, select, relay, fallback, url-test
  tolerance: 300
    # lazy: true
  url: http://www.gstatic.com/generate_204
  interval: 300
    # strategy: consistent-hashing # or round-robin  # 负载均衡策略
  proxies:
  - 🇺🇸美国-科罗拉多-0-v2ray-143.198.237.214:27489
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:49719
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:49468
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:48794
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:48089
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:47861
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:47553
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:45948
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:41306
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:40711
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:39171
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:38747
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:38620
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:32843
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:32558
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:31764
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:31572
  - 🇺🇸美国-新泽西-0-ss-156.146.33.66:49126
  - 🇺🇸美国-新泽西-0-ss-156.146.33.66:38620
  - 🇺🇸美国-新泽西-0-ss-156.146.33.66:34687
  - 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:39772
  - 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:33992
  - 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:31572
  - 🇺🇸美国-0-0-v2ray-18.162.214.245:8888
  - 🇸🇬新加坡-0-0-v2ray-139.59.254.17:12081
  - 🇸🇬新加坡-0-0-v2ray-139.59.122.24:34715
  - 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:47121
  - 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:46726
  - 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:44742
  - 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:44102
  - 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:36460
  - 🇷🇺俄罗斯-Novosibirskaya-0-v2ray-91.206.92.27:55183
  - 🇵🇱波兰-华沙-0-ss-5.253.206.229:40093
  - 🇳🇿新西兰-0-0-ss-107.150.94.12:38620
  - 🇳🇿新西兰-0-0-ss-107.150.94.12:31572
  - 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:8091
  - 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:443
  - 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:2376
  - 🇳🇴挪威-Vest-Agder-0-ss-46.29.218.6:2375
  - 🇰🇷韩国-首尔-首尔-v2ray-3.38.95.113:1234
  - 🇯🇵日本-东京都-东京-v2ray-54.238.161.11:80
  - 🇯🇵日本-东京都-东京-ss-89.187.161.4:40093
  - 🇯🇵日本-东京都-东京-ss-89.187.161.4:39772
  - 🇮🇹意大利-米兰-米兰-ss-212.102.54.163:47861
  - 🇮🇹意大利-米兰-米兰-ss-212.102.54.163:44820
  - 🇮🇹意大利-米兰-米兰-ss-212.102.54.163:41738
  - 🇮🇹意大利-米兰-米兰-ss-212.102.54.161:42304
  - 🇮🇹意大利-米兰-米兰-ss-212.102.54.161:40282
  - 🇮🇹意大利-米兰-米兰-ss-212.102.54.161:33998
  - 🇩🇰丹麦-0-0-ss-185.108.106.175:41992
  - 🇩🇰丹麦-0-0-ss-185.108.106.172:42816
  - 🇩🇪德国-法兰克福-法兰克福-ss-172.105.251.193:2376
  - 🇨🇳中国-福建-泉州-ssr-117.28.243.132:8333
  - 🇨🇳中国-福建-泉州-ss-117.28.243.132:8333
  - 🇨🇳中国-上海-上海-ss-101.91.121.247:50004
  - 🇨🇦加拿大-安大略-多伦多-ss-198.57.27.218:8090
rules:
  # 黑名单模式，命中规则使用代理
- PROCESS-NAME,v2ray,DIRECT
- PROCESS-NAME,xray,DIRECT
- PROCESS-NAME,naive,DIRECT
- PROCESS-NAME,trojan,DIRECT
- PROCESS-NAME,trojan-go,DIRECT
- PROCESS-NAME,ss-local,DIRECT
- PROCESS-NAME,privoxy,DIRECT
- PROCESS-NAME,leaf,DIRECT
- PROCESS-NAME,v2ray.exe,DIRECT
- PROCESS-NAME,xray.exe,DIRECT
- PROCESS-NAME,naive.exe,DIRECT
- PROCESS-NAME,trojan.exe,DIRECT
- PROCESS-NAME,trojan-go.exe,DIRECT
- PROCESS-NAME,ss-local.exe,DIRECT
- PROCESS-NAME,privoxy.exe,DIRECT
- PROCESS-NAME,leaf.exe,DIRECT
- PROCESS-NAME,Surge,DIRECT
- PROCESS-NAME,Surge 2,DIRECT
- PROCESS-NAME,Surge 3,DIRECT
- PROCESS-NAME,Surge 4,DIRECT
- PROCESS-NAME,Surge%202,DIRECT
- PROCESS-NAME,Surge%203,DIRECT
- PROCESS-NAME,Surge%204,DIRECT
- PROCESS-NAME,Thunder,DIRECT
- PROCESS-NAME,DownloadService,DIRECT
- PROCESS-NAME,qBittorrent,DIRECT
- PROCESS-NAME,Transmission,DIRECT
- PROCESS-NAME,fdm,DIRECT
- PROCESS-NAME,aria2c,DIRECT
- PROCESS-NAME,Folx,DIRECT
- PROCESS-NAME,NetTransport,DIRECT
- PROCESS-NAME,uTorrent,DIRECT
- PROCESS-NAME,WebTorrent,DIRECT
- PROCESS-NAME,aria2c.exe,DIRECT
- PROCESS-NAME,BitComet.exe,DIRECT
- PROCESS-NAME,fdm.exe,DIRECT
- PROCESS-NAME,NetTransport.exe,DIRECT
- PROCESS-NAME,qbittorrent.exe,DIRECT
- PROCESS-NAME,Thunder.exe,DIRECT
- PROCESS-NAME,ThunderVIP.exe,DIRECT
- PROCESS-NAME,transmission-daemon.exe,DIRECT
- PROCESS-NAME,transmission-qt.exe,DIRECT
- PROCESS-NAME,uTorrent.exe,DIRECT
- PROCESS-NAME,WebTorrent.exe,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- GEOIP,CN,DIRECT
- MATCH,PROXY
