port: 7890
socks-port: 1080 # SOCKS5代理端口，DNS请求会中转
redir-port: 3333 # 透明代理端口
allow-lan: true
mode: Rule
log-level: info
external-controller: 0.0.0.0:9090
secret: route

# 透明代理开启DNS
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: true # lookup hosts and return IP record
  nameserver:
  - tls://doh.pub:853   # DNSpod DoT
  - https://doh.pub/dns-query   # DNSpod DoH
  - 119.29.29.29   # DNSpod DNS 17ms
  # 提供 fallback 时，如果GEOIP非 CN 中国时使用 fallback 解析
  fallback:
  - tls://8.8.8.8:853   # Google DNS over TLS
  - tls://1.1.1.1:853   # cloudflare DNS over TLS
  - https://dns.google/dns-query   # Google DNS over HTTPS
  - https://cloudflare-dns.com/dns-query   # cloudflare DNS over HTTPS
  # 强制DNS解析使用`fallback`配置
  fallback-filter:
    # true: CN使用nameserver解析，非CN使用fallback
    geoip: true
    # geoip设置为false时有效： 不匹配`ipcidr`地址时会使用`nameserver`结果，匹配`ipcidr`地址时使用`fallback`结果。
    ipcidr:
    - 240.0.0.0/4


# 配置规则参考文档： https://github.com/Dreamacro/clash/wiki/configuration
# 设置代理提供者(远程订阅地址+本地订阅文件)
# proxy-providers:
#   provider_file:
#     type: file
#     path: ./provider_local.yaml
#     health-check:
#       enable: true
#       interval: 600
#       url: http://www.gstatic.com/generate_204
#   provider_url:
#     type: file
#     path: ./provider_remote.yaml
#     health-check:
#       enable: true
#       interval: 600
#       url: http://www.gstatic.com/generate_204
#
#
# DIY组保留的个人节点
proxies:
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:48794
  type: ss
  server: 156.146.33.74
  port: 48794
  cipher: aes-256-gcm
  password: r9Q3adc3ru9sfBDPEj4yp6U6
- name: 🇳🇿新西兰-0-0-ss-107.150.94.12:41992
  type: ss
  server: 107.150.94.12
  port: 41992
  cipher: aes-256-gcm
  password: XmQSxDCn5ehpcq6DBYms8FJf
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:47861
  type: ss
  server: 2.58.241.133
  port: 47861
  cipher: aes-256-gcm
  password: LJcChRsGQRhywrtXUU55TLTu
- name: 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:37588
  type: ss
  server: 185.76.9.56
  port: 37588
  cipher: aes-256-gcm
  password: kD9vkjnE6dsUzwQfvKkPkQAd
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:41372
  type: ss
  server: 2.58.241.133
  port: 41372
  cipher: aes-256-gcm
  password: 5kGAhC3AmVC35GbruHjSrZf2
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:46642
  type: ss
  server: 198.8.92.84
  port: 46642
  cipher: aes-256-gcm
  password: gYL83DQWXuDbxmZAVVtUTXaK
- name: 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:40282
  type: ss
  server: 185.76.9.56
  port: 40282
  cipher: aes-256-gcm
  password: Pvvaw486867D2w4yctL2ULTQ
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:44745
  type: ss
  server: 2.58.241.133
  port: 44745
  cipher: aes-256-gcm
  password: fyXdw87yCH9SAmFkPvsvLVqC
- name: 🇨🇳中国-香港-0-ss-118.107.244.110:7307
  type: ss
  server: 118.107.244.110
  port: 7307
  cipher: aes-256-gcm
  password: FoOiGlkAA9yPEGP
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.131:50168
  type: ss
  server: 2.58.241.131
  port: 50168
  cipher: aes-256-gcm
  password: WCuz7yrfZSCQQXSNrtGPz2HT
- name: 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:31572
  type: ss
  server: 198.147.22.87
  port: 31572
  cipher: aes-256-gcm
  password: n8w4StnbVD9dmXYn4Ajt87EA
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:41676
  type: ss
  server: 2.58.241.133
  port: 41676
  cipher: aes-256-gcm
  password: z6pH3RyttkRWhJ5tpRyt6dYk
- name: 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:38620
  type: ss
  server: 185.76.8.218
  port: 38620
  cipher: aes-256-gcm
  password: Kquv5UhvZXNMemAQy8DxZ7qn
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.131:49396
  type: ss
  server: 2.58.241.131
  port: 49396
  cipher: aes-256-gcm
  password: BdRWC38L5JUDMTYNNxJGcUwB
- name: 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:47121
  type: ss
  server: 185.76.9.56
  port: 47121
  cipher: aes-256-gcm
  password: CTK8GXFQgKYQErrghPJfZ6tk
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:38747
  type: ss
  server: 2.58.241.133
  port: 38747
  cipher: aes-256-gcm
  password: RtbLkxbJZpUQ6m8y4qAeLYZj
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:42304
  type: ss
  server: 2.58.241.133
  port: 42304
  cipher: aes-256-gcm
  password: p26v2JwhQVHDHsXk66fXt56r
- name: 🇳🇿新西兰-0-0-ss-107.150.94.12:31572
  type: ss
  server: 107.150.94.12
  port: 31572
  cipher: aes-256-gcm
  password: n8w4StnbVD9dmXYn4Ajt87EA
- name: 🇨🇦加拿大-安大略-多伦多-ss-198.57.27.218:2376
  type: ss
  server: 198.57.27.218
  port: 2376
  cipher: aes-256-gcm
  password: faBAoD54k87UJG7
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:37473
  type: ss
  server: 2.58.241.133
  port: 37473
  cipher: aes-256-gcm
  password: enctdKyJfSu76VqznKwTt6Ap
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:46726
  type: ss
  server: 2.58.241.133
  port: 46726
  cipher: aes-256-gcm
  password: 2fqKbFPGHpcmMTJzGsUbsfYf
- name: 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:39772
  type: ss
  server: 198.147.22.87
  port: 39772
  cipher: aes-256-gcm
  password: CUndSZnYsPKcu6Kj8THVMBHD
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:38620
  type: ss
  server: 2.58.241.133
  port: 38620
  cipher: aes-256-gcm
  password: Kquv5UhvZXNMemAQy8DxZ7qn
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:31764
  type: ss
  server: 156.146.33.74
  port: 31764
  cipher: aes-256-gcm
  password: YgusH2MWA8PWc3p2VDsR7AVv
- name: 🇳🇿新西兰-0-0-ss-107.150.94.14:38620
  type: ss
  server: 107.150.94.14
  port: 38620
  cipher: aes-256-gcm
  password: Kquv5UhvZXNMemAQy8DxZ7qn
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:39772
  type: ss
  server: 2.58.241.133
  port: 39772
  cipher: aes-256-gcm
  password: CUndSZnYsPKcu6Kj8THVMBHD
- name: 🇨🇳中国-福建-泉州-ss-117.28.243.169:8333
  type: ss
  server: 117.28.243.169
  port: 8333
  cipher: rc4-md5
  password: passfw2xs4e!
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:48938
  type: ss
  server: 156.146.33.74
  port: 48938
  cipher: aes-256-gcm
  password: 4ejJ8n5ddLuYDUHGXJre2ufJ
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:35371
  type: ss
  server: 2.58.241.133
  port: 35371
  cipher: aes-256-gcm
  password: pjeDhAJGuML8xKUxcjRqq6a9
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.131:49719
  type: ss
  server: 2.58.241.131
  port: 49719
  cipher: aes-256-gcm
  password: 42SjT9vBF6ma9eFF3URaJpQ4
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.66:49126
  type: ss
  server: 156.146.33.66
  port: 49126
  cipher: aes-256-gcm
  password: wrCaGtrUbzeRqQLdc8Kmk3Nd
- name: 🇺🇸美国-新泽西-0-ss-156.146.33.74:49468
  type: ss
  server: 156.146.33.74
  port: 49468
  cipher: aes-256-gcm
  password: LsYSQDxmPj9AcWpSX5HrYfu6
- name: 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:50168
  type: ss
  server: 185.76.8.218
  port: 50168
  cipher: aes-256-gcm
  password: WCuz7yrfZSCQQXSNrtGPz2HT
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.131:48794
  type: ss
  server: 2.58.241.131
  port: 48794
  cipher: aes-256-gcm
  password: r9Q3adc3ru9sfBDPEj4yp6U6
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.131:47553
  type: ss
  server: 2.58.241.131
  port: 47553
  cipher: aes-256-gcm
  password: t2JnnFqjDMmzWurseJPgBsYY
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:38742
  type: ss
  server: 2.58.241.133
  port: 38742
  cipher: aes-256-gcm
  password: DKXfWwc4ebscpXTKpbt85rSH
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.131:50232
  type: ss
  server: 2.58.241.131
  port: 50232
  cipher: aes-256-gcm
  password: CjchzpwdSjRtDjezYMwx9BKM
- name: 欧洲-0-0-ss-138.199.42.170:49396
  type: ss
  server: 138.199.42.170
  port: 49396
  cipher: aes-256-gcm
  password: BdRWC38L5JUDMTYNNxJGcUwB
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:49126
  type: ss
  server: 2.58.241.133
  port: 49126
  cipher: aes-256-gcm
  password: wrCaGtrUbzeRqQLdc8Kmk3Nd
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:49339
  type: ss
  server: 2.58.241.133
  port: 49339
  cipher: aes-256-gcm
  password: suucSeVLmt6PQKAP77NtGw9x
- name: 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:44236
  type: ss
  server: 198.8.92.84
  port: 44236
  cipher: aes-256-gcm
  password: FWrXcxPZjJxAN89xLgqY3Acp
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.131:49468
  type: ss
  server: 2.58.241.131
  port: 49468
  cipher: aes-256-gcm
  password: LsYSQDxmPj9AcWpSX5HrYfu6
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:42185
  type: ss
  server: 2.58.241.133
  port: 42185
  cipher: aes-256-gcm
  password: FaTG4zALZru72gxjgSHQ7Jdh
- name: 🇸🇬新加坡-0-0-ss-51.79.166.171:50004
  type: ss
  server: 51.79.166.171
  port: 50004
  cipher: aes-256-cfb
  password: '4415934295'
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:31944
  type: ss
  server: 2.58.241.133
  port: 31944
  cipher: aes-256-gcm
  password: aYNeKDMzYQYw4KbUbJA8Wszq
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:48938
  type: ss
  server: 2.58.241.133
  port: 48938
  cipher: aes-256-gcm
  password: 4ejJ8n5ddLuYDUHGXJre2ufJ
- name: 🇨🇳中国-台湾-台北-ss-2.58.241.133:44742
  type: ss
  server: 2.58.241.133
  port: 44742
  cipher: aes-256-gcm
  password: QCStKzZ56SHBc4tL7stCEqqd
- name: 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:34815
  type: ss
  server: 185.76.9.56
  port: 34815
  cipher: aes-256-gcm
  password: LkFAzkzXkSCRYa2CsRdL8cGb
- name: 🇨🇳中国-福建-泉州-ssr-117.28.243.132:8333
  type: ssr
  server: 117.28.243.132
  password: passfw2xs4e!
  obfs: plain
  protocol: origin
  port: 8333
  cipher: rc4-md5
  protocol-param: ''
  obfs-param: ''
- name: 🇺🇸美国-加利福尼亚-0-v2ray-45.32.74.58:43320
  type: vmess
  server: 45.32.74.58
  network: ws
  port: 43320
  uuid: 207f01a0-4621-11ec-8b00-560003ae8b46
  alterId: 4
  cipher: auto
  tls: false
  ws-path: /hZqt4s9f/
- name: 🇺🇸美国-德克萨斯-0-v2ray-159.223.75.43:56776
  type: vmess
  server: 159.223.75.43
  network: ws
  port: 56776
  uuid: 2a1620a3-dc12-4d2e-faa9-809028d3e191
  alterId: 4
  cipher: auto
  tls: false
  ws-path: /
- name: 🇯🇵日本-东京都-东京-v2ray-54.238.161.11:80
  type: vmess
  server: 54.238.161.11
  network: ws
  port: 80
  uuid: 261aeb5f-b6f7-359c-a321-9794bf344e12
  alterId: 4
  cipher: auto
  tls: false
  ws-path: /v2ray

proxy-groups:
# 类型选择 简介
# select : 用于选择代理或代理组, 可以通过 RESTful API 来切换代理，建议在 GUI 中使用
# load-balance : 相同eTLD+1的请求将拨号到同一个代理。
# url-test : 通过对 URL 的速度进行基准测试来选择将使用哪个代理。
# fallback : 按优先级选择可用的策略。通过访问 URL 来测试可用性，就像自动 url-test 组一样。
# relay : 中继链接代理。代理不应包含中继。不支持 UDP。 流量：Clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet 
#  
# 推荐选择：
#   命令行服务建议选择 url-test / fallback / load-balance
#   GUI窗口 官方建议选择 select ，当然也推荐使用url-test 自动检测可用性。
- name: PROXY
  type: select   # load-balance, select, relay, fallback, url-test
  tolerance: 300
    # lazy: true
  url: http://www.gstatic.com/generate_204
  interval: 300
    # strategy: consistent-hashing # or round-robin  # 负载均衡策略
  proxies:
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:49468
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:48938
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:48794
  - 🇺🇸美国-新泽西-0-ss-156.146.33.74:31764
  - 🇺🇸美国-新泽西-0-ss-156.146.33.66:49126
  - 🇺🇸美国-德克萨斯-0-v2ray-159.223.75.43:56776
  - 🇺🇸美国-加利福尼亚-0-v2ray-45.32.74.58:43320
  - 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:39772
  - 🇺🇸美国-佛罗里达-0-ss-198.147.22.87:31572
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:46642
  - 🇺🇸美国-佐治亚-亚特兰大-ss-198.8.92.84:44236
  - 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:50168
  - 🇸🇰斯洛伐克-0-0-ss-185.76.8.218:38620
  - 🇸🇬新加坡-0-0-ss-51.79.166.171:50004
  - 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:47121
  - 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:40282
  - 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:37588
  - 🇸🇪瑞典-斯德哥尔摩-0-ss-185.76.9.56:34815
  - 🇳🇿新西兰-0-0-ss-107.150.94.14:38620
  - 🇳🇿新西兰-0-0-ss-107.150.94.12:41992
  - 🇳🇿新西兰-0-0-ss-107.150.94.12:31572
  - 🇯🇵日本-东京都-东京-v2ray-54.238.161.11:80
  - 🇨🇳中国-香港-0-ss-118.107.244.110:7307
  - 🇨🇳中国-福建-泉州-ssr-117.28.243.132:8333
  - 🇨🇳中国-福建-泉州-ss-117.28.243.169:8333
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:49339
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:49126
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:48938
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:47861
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:46726
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:44745
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:44742
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:42304
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:42185
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:41676
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:41372
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:39772
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:38747
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:38742
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:38620
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:37473
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:35371
  - 🇨🇳中国-台湾-台北-ss-2.58.241.133:31944
  - 🇨🇳中国-台湾-台北-ss-2.58.241.131:50232
  - 🇨🇳中国-台湾-台北-ss-2.58.241.131:50168
  - 🇨🇳中国-台湾-台北-ss-2.58.241.131:49719
  - 🇨🇳中国-台湾-台北-ss-2.58.241.131:49468
  - 🇨🇳中国-台湾-台北-ss-2.58.241.131:49396
  - 🇨🇳中国-台湾-台北-ss-2.58.241.131:48794
  - 🇨🇳中国-台湾-台北-ss-2.58.241.131:47553
  - 🇨🇦加拿大-安大略-多伦多-ss-198.57.27.218:2376
  - 欧洲-0-0-ss-138.199.42.170:49396
rules:
  # 黑名单模式，命中规则使用代理
- PROCESS-NAME,v2ray,DIRECT
- PROCESS-NAME,xray,DIRECT
- PROCESS-NAME,naive,DIRECT
- PROCESS-NAME,trojan,DIRECT
- PROCESS-NAME,trojan-go,DIRECT
- PROCESS-NAME,ss-local,DIRECT
- PROCESS-NAME,privoxy,DIRECT
- PROCESS-NAME,leaf,DIRECT
- PROCESS-NAME,v2ray.exe,DIRECT
- PROCESS-NAME,xray.exe,DIRECT
- PROCESS-NAME,naive.exe,DIRECT
- PROCESS-NAME,trojan.exe,DIRECT
- PROCESS-NAME,trojan-go.exe,DIRECT
- PROCESS-NAME,ss-local.exe,DIRECT
- PROCESS-NAME,privoxy.exe,DIRECT
- PROCESS-NAME,leaf.exe,DIRECT
- PROCESS-NAME,Surge,DIRECT
- PROCESS-NAME,Surge 2,DIRECT
- PROCESS-NAME,Surge 3,DIRECT
- PROCESS-NAME,Surge 4,DIRECT
- PROCESS-NAME,Surge%202,DIRECT
- PROCESS-NAME,Surge%203,DIRECT
- PROCESS-NAME,Surge%204,DIRECT
- PROCESS-NAME,Thunder,DIRECT
- PROCESS-NAME,DownloadService,DIRECT
- PROCESS-NAME,qBittorrent,DIRECT
- PROCESS-NAME,Transmission,DIRECT
- PROCESS-NAME,fdm,DIRECT
- PROCESS-NAME,aria2c,DIRECT
- PROCESS-NAME,Folx,DIRECT
- PROCESS-NAME,NetTransport,DIRECT
- PROCESS-NAME,uTorrent,DIRECT
- PROCESS-NAME,WebTorrent,DIRECT
- PROCESS-NAME,aria2c.exe,DIRECT
- PROCESS-NAME,BitComet.exe,DIRECT
- PROCESS-NAME,fdm.exe,DIRECT
- PROCESS-NAME,NetTransport.exe,DIRECT
- PROCESS-NAME,qbittorrent.exe,DIRECT
- PROCESS-NAME,Thunder.exe,DIRECT
- PROCESS-NAME,ThunderVIP.exe,DIRECT
- PROCESS-NAME,transmission-daemon.exe,DIRECT
- PROCESS-NAME,transmission-qt.exe,DIRECT
- PROCESS-NAME,uTorrent.exe,DIRECT
- PROCESS-NAME,WebTorrent.exe,DIRECT
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
- GEOIP,CN,DIRECT
- MATCH,PROXY
