port: 7890
socks-port: 1080 # SOCKS5代理端口，DNS请求会中转
redir-port: 3333 # 透明代理端口
allow-lan: true
mode: Rule
log-level: info # 日志显示级别： debug-问题调试，info-基本信息
external-controller: 0.0.0.0:9090
secret: route
hosts:
  router.asus.com: 192.168.50.1
# 透明代理开启DNS
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: redir-host # redir-host or fake-ip
  fake-ip-range: 198.18.0.1/16 # Fake IP addresses pool CIDR
  use-hosts: false # lookup hosts and return IP record
  nameserver:
  - 114.114.114.114
  # 提供 fallback 时，如果GEOIP非 CN 中国时使用 fallback 解析
  fallback:
  - 8.8.8.8   # Google DNS over TCP
  - 1.1.1.1   # cloudflare DNS over TCP
  - tls://8.8.8.8:853   # Google DNS over TLS
  - tls://1.1.1.1:853   # cloudflare DNS over TLS
  - https://dns.google/dns-query   # Google DNS over HTTPS
  - https://cloudflare-dns.com/dns-query   # cloudflare DNS over HTTPS
  # 强制DNS解析使用`fallback`配置
  fallback-filter:
    # true: CN使用nameserver解析，非CN使用fallback
    geoip: true
    # geoip设置为false时有效： 不匹配`ipcidr`地址时会使用`nameserver`结果，匹配`ipcidr`地址时使用`fallback`结果。
    ipcidr:
    - 240.0.0.0/4
# 个人节点
proxies:
- name: 🇯🇵:日本-ss-89.31.126.150:802-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  type: ss
  server: 89.31.126.150
  password: G!yBwPWH3Vao
  port: 802
  cipher: chacha20-ietf-poly1305
- name: 🇨🇦:加拿大-ss-72.140.224.197:808-被墙-直连-解锁加拿大地区NF非自制剧
  type: ss
  server: 72.140.224.197
  password: G!yBwPWH3Vao
  port: 808
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-38.68.134.37:7306-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.37
  password: FoOiGlkAA9yPEGP
  port: 7306
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.68.134.196:808-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.196
  password: G!yBwPWH3Vao
  port: 808
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-38.75.137.187:3306-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.75.137.187
  password: Y6R9pAtvxxzmGC
  port: 3306
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.68.134.37:5003-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.37
  password: g5MeD6Ft3CWlJId
  port: 5003
  cipher: aes-256-gcm
- name: 🇨🇦:加拿大-ss-72.140.224.197:811-被墙-直连-解锁加拿大地区NF非自制剧
  type: ss
  server: 72.140.224.197
  password: G!yBwPWH3Vao
  port: 811
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-38.91.101.221:7306-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.91.101.221
  password: FoOiGlkAA9yPEGP
  port: 7306
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.75.137.187:2376-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.75.137.187
  password: faBAoD54k87UJG7
  port: 2376
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.68.134.196:812-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.196
  password: G!yBwPWH3Vao
  port: 812
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-38.68.134.37:2375-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.37
  password: faBAoD54k87UJG7
  port: 2375
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.68.134.48:3389-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.48
  password: Y6R9pAtvxxzmGC
  port: 3389
  cipher: aes-256-gcm
- name: 🇨🇦:加拿大-ss-72.140.224.197:805-被墙-直连-解锁加拿大地区NF非自制剧
  type: ss
  server: 72.140.224.197
  password: G!yBwPWH3Vao
  port: 805
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-38.75.137.187:8080-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.75.137.187
  password: KixLvKzwjekG00rm
  port: 8080
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.91.101.221:5004-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.91.101.221
  password: g5MeD6Ft3CWlJId
  port: 5004
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-167.88.63.99:8090-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 167.88.63.99
  password: PCnnH6SQSnfoS27
  port: 8090
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-167.88.63.107:2375-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 167.88.63.107
  password: faBAoD54k87UJG7
  port: 2375
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-167.88.62.62:2375-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 167.88.62.62
  password: faBAoD54k87UJG7
  port: 2375
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.75.137.187:2375-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.75.137.187
  password: faBAoD54k87UJG7
  port: 2375
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.68.134.48:2375-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.48
  password: faBAoD54k87UJG7
  port: 2375
  cipher: aes-256-gcm
- name: 🇹🇷:土耳其-ss-185.17.113.234:804-被墙-直连-解锁土耳其地区NF非自制剧
  type: ss
  server: 185.17.113.234
  password: G!yBwPWH3Vao
  port: 804
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-167.88.63.99:8091-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 167.88.63.99
  password: PCnnH6SQSnfoS27
  port: 8091
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-167.88.62.62:5004-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 167.88.62.62
  password: g5MeD6Ft3CWlJId
  port: 5004
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.68.134.37:8090-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.37
  password: PCnnH6SQSnfoS27
  port: 8090
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-167.88.62.62:3389-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 167.88.62.62
  password: Y6R9pAtvxxzmGC
  port: 3389
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-167.88.63.99:2376-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 167.88.63.99
  password: faBAoD54k87UJG7
  port: 2376
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.121.43.51:2376-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.121.43.51
  password: faBAoD54k87UJG7
  port: 2376
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.68.134.37:7307-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.37
  password: FoOiGlkAA9yPEGP
  port: 7307
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-167.88.63.99:7307-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 167.88.63.99
  password: FoOiGlkAA9yPEGP
  port: 7307
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.68.135.208:3389-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.135.208
  password: Y6R9pAtvxxzmGC
  port: 3389
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.75.137.187:3389-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.75.137.187
  password: Y6R9pAtvxxzmGC
  port: 3389
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.91.101.221:7307-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.91.101.221
  password: FoOiGlkAA9yPEGP
  port: 7307
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-167.88.62.62:8090-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 167.88.62.62
  password: PCnnH6SQSnfoS27
  port: 8090
  cipher: aes-256-gcm
- name: 🇺🇸:美国-ss-38.68.134.196:810-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.196
  password: G!yBwPWH3Vao
  port: 810
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-38.68.134.196:805-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.196
  password: G!yBwPWH3Vao
  port: 805
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-167.88.63.107:8091-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 167.88.63.107
  password: PCnnH6SQSnfoS27
  port: 8091
  cipher: aes-256-gcm
- name: 🇨🇦:加拿大-ss-72.140.224.197:806-被墙-直连-解锁加拿大地区NF非自制剧
  type: ss
  server: 72.140.224.197
  password: G!yBwPWH3Vao
  port: 806
  cipher: chacha20-ietf-poly1305
- name: 🇨🇦:加拿大-ss-72.140.224.197:812-被墙-直连-解锁加拿大地区NF非自制剧
  type: ss
  server: 72.140.224.197
  password: G!yBwPWH3Vao
  port: 812
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-38.68.134.196:800-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 38.68.134.196
  password: G!yBwPWH3Vao
  port: 800
  cipher: chacha20-ietf-poly1305
- name: 🇺🇸:美国-ss-167.88.63.107:2376-被墙-直连-解锁美国地区NF非自制剧
  type: ss
  server: 167.88.63.107
  password: faBAoD54k87UJG7
  port: 2376
  cipher: aes-256-gcm
- name: 🇯🇵:日本-ss-89.31.126.150:812-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  type: ss
  server: 89.31.126.150
  password: G!yBwPWH3Vao
  port: 812
  cipher: chacha20-ietf-poly1305
- name: 🇨🇾:塞浦路斯-ss-213.169.137.221:989-被墙-直连-解锁塞浦路斯地区NF非自制剧
  type: ss
  server: 213.169.137.221
  password: f8f7aCzcPKbsF8p3
  port: 989
  cipher: aes-256-cfb
- name: 🇮🇱:以色列-ss-31.133.100.49:50004-被墙-直连-解锁以色列地区NF非自制剧
  type: ss
  server: 31.133.100.49
  password: '4415934295'
  port: 50004
  cipher: aes-256-cfb
- name: 🇨🇳:中国-ss-59.125.11.158:8158-被墙-中转:59.125.11.159-解锁台湾地区NF非自制剧
  type: ss
  server: 59.125.11.158
  password: passinfo123
  port: 8158
  cipher: rc4-md5
- name: 🇷🇺:俄罗斯-ss-83.217.9.76:989-被墙-直连-解锁俄罗斯联邦地区NF非自制剧
  type: ss
  server: 83.217.9.76
  password: f8f7aCzcPKbsF8p3
  port: 989
  cipher: aes-256-cfb

# 类型选择 简介
# select : 用于选择代理或代理组, 可以通过 RESTful API 来切换代理，建议在 GUI 中使用
# load-balance : 相同eTLD+1的请求将拨号到同一个代理。
# url-test : 通过对 URL 的速度进行基准测试来选择将使用哪个代理。
# fallback : 按优先级选择可用的策略。通过访问 URL 来测试可用性，就像自动 url-test 组一样。
# relay : 中继链接代理。代理不应包含中继。不支持 UDP。 流量：Clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet 
#  
# 推荐选择：
#   命令行服务建议选择 url-test / fallback / load-balance
#   GUI窗口 官方建议选择 select ，当然也推荐使用url-test 自动检测可用性。
proxy-groups:
  # 保留的自定义节点
- name: PROXY
  type: select   # load-balance, select, relay, fallback, url-test
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
- name: 被墙代理组
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - 🇺🇸:美国-ss-38.91.101.221:7307-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.91.101.221:7306-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.91.101.221:5004-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.75.137.187:8080-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.75.137.187:3389-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.75.137.187:3306-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.75.137.187:2376-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.75.137.187:2375-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.135.208:3389-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.48:3389-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.48:2375-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.37:8090-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.37:7307-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.37:7306-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.37:5003-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.37:2375-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.196:812-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.196:810-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.196:808-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.196:805-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.68.134.196:800-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-38.121.43.51:2376-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-167.88.63.99:8091-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-167.88.63.99:8090-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-167.88.63.99:7307-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-167.88.63.99:2376-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-167.88.63.107:8091-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-167.88.63.107:2376-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-167.88.63.107:2375-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-167.88.62.62:8090-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-167.88.62.62:5004-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-167.88.62.62:3389-被墙-直连-解锁美国地区NF非自制剧
  - 🇺🇸:美国-ss-167.88.62.62:2375-被墙-直连-解锁美国地区NF非自制剧
  - 🇹🇷:土耳其-ss-185.17.113.234:804-被墙-直连-解锁土耳其地区NF非自制剧
  - 🇷🇺:俄罗斯-ss-83.217.9.76:989-被墙-直连-解锁俄罗斯联邦地区NF非自制剧
  - 🇯🇵:日本-ss-89.31.126.150:812-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  - 🇯🇵:日本-ss-89.31.126.150:802-被墙-中转:185.160.26.231-解锁日本地区NF非自制剧
  - 🇮🇱:以色列-ss-31.133.100.49:50004-被墙-直连-解锁以色列地区NF非自制剧
  - 🇨🇾:塞浦路斯-ss-213.169.137.221:989-被墙-直连-解锁塞浦路斯地区NF非自制剧
  - 🇨🇳:中国-ss-59.125.11.158:8158-被墙-中转:59.125.11.159-解锁台湾地区NF非自制剧
  - 🇨🇦:加拿大-ss-72.140.224.197:812-被墙-直连-解锁加拿大地区NF非自制剧
  - 🇨🇦:加拿大-ss-72.140.224.197:811-被墙-直连-解锁加拿大地区NF非自制剧
  - 🇨🇦:加拿大-ss-72.140.224.197:808-被墙-直连-解锁加拿大地区NF非自制剧
  - 🇨🇦:加拿大-ss-72.140.224.197:806-被墙-直连-解锁加拿大地区NF非自制剧
  - 🇨🇦:加拿大-ss-72.140.224.197:805-被墙-直连-解锁加拿大地区NF非自制剧
- name: 仅支持Netflix自制剧
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
- name: 解锁Netflix非自制剧
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
- name: 入口代理组
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 仅支持Netflix自制剧
  - 解锁Netflix非自制剧
  - PROXY
- name: 出口代理组
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 被墙代理组
  - 仅支持Netflix自制剧
  - 解锁Netflix非自制剧
- name: RELAY_PROXY
    # 中继代理组,不支持UDP协议。线路: clash <-> vmess <-> ss1 <-> ss2 <-> Internet
  type: relay
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 入口代理组
  - 出口代理组
- name: NETFLIX_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
  - DIRECT
- name: Tiktok_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
  - DIRECT
- name: Bili_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY
- name: IQiyi_PROXY
  type: select
  url: http://www.gstatic.com/generate_204
  interval: 300
  proxies:
  - DIRECT
  - PROXY
  - 解锁Netflix非自制剧
  - 仅支持Netflix自制剧
  - RELAY_PROXY

# 黑名单模式，命中规则使用代理
rules:
- DOMAIN,clash.razord.top,DIRECT
- DOMAIN,yacd.haishan.me,DIRECT
  # > Netflix
- DOMAIN-SUFFIX,netflix.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflix.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxext.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflximg.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflximg.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxso.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,nflxvideo.net,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest0.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest1.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest2.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest3.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest4.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest5.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest6.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest7.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest8.com,NETFLIX_PROXY
- DOMAIN-SUFFIX,netflixdnstest9.com,NETFLIX_PROXY
  # Netflix测速网站
- DOMAIN-SUFFIX,fast.com,NETFLIX_PROXY
  # - RULE-SET,video_netflix,NETFLIX_PROXY
  # > TikTok
- PROCESS-NAME,com.ss.android.ugc.trill,Tiktok_PROXY
- DOMAIN-SUFFIX,byteoversea.com,Tiktok_PROXY
- DOMAIN-SUFFIX,ibytedtos.com,Tiktok_PROXY
- DOMAIN-SUFFIX,ipstatp.com,Tiktok_PROXY
- DOMAIN-SUFFIX,muscdn.com,Tiktok_PROXY
- DOMAIN-SUFFIX,musical.ly,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktok.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tik-tokapi.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktokcdn.com,Tiktok_PROXY
- DOMAIN-SUFFIX,tiktokv.com,Tiktok_PROXY
  # - RULE-SET,video_tiktok,Tiktok_PROXY
  # > iQIYI
- DOMAIN-SUFFIX,iq.com,IQiyi_PROXY
- DOMAIN,intl.iqiyi.com,IQiyi_PROXY
- DOMAIN,intl-rcd.iqiyi.com,IQiyi_PROXY
- DOMAIN,intl-subscription.iqiyi.com,IQiyi_PROXY
  # - RULE-SET,video_iqiyi,IQiyi_PROXY
  # > Bilibili
- PROCESS-NAME,com.bilibili.app.in,Bili_PROXY
- PROCESS-NAME,tv.danmaku.bili,Bili_PROXY
- DOMAIN-SUFFIX,acg.tv,Bili_PROXY
- DOMAIN-SUFFIX,acgvideo.com,Bili_PROXY
- DOMAIN-SUFFIX,b23.tv,Bili_PROXY
- DOMAIN-SUFFIX,biliapi.com,Bili_PROXY
- DOMAIN-SUFFIX,biliapi.net,Bili_PROXY
- DOMAIN-SUFFIX,bilibili.com,Bili_PROXY
- DOMAIN-SUFFIX,biligame.com,Bili_PROXY
- DOMAIN-SUFFIX,biligame.net,Bili_PROXY
- DOMAIN-SUFFIX,bilivideo.com,Bili_PROXY
- DOMAIN-SUFFIX,hdslb.com,Bili_PROXY
- DOMAIN-SUFFIX,im9.com,Bili_PROXY
- DOMAIN-SUFFIX,smtcdns.net,Bili_PROXY
  # 后面追加规则
